### ISSUE TITLE
Oculus Gear VR deep linking 

### ISSUE THREAD

**Issue by dustinkerstein** [BranchMetrics/unity-branch-deep-linking-attribution#101]
I figure this is likely not possible, but I wanted to ask anyway. Based on the Gear VR [submission requirements](https://developer.oculus.com/distribute/latest/concepts/publish-mobile-manifest/) it specifies: 

> You must have android.intent.category.INFO, instead of android.internet.category.LAUNCHER. Your app must only appear in Oculus Home. It must not appear in the phone’s launcher.

That means that Branch won't be able to deep link, correct? Any thoughts on potential workarounds? Thanks!

**Comment by antonargunov** [comment]
@dustinkerstein , yes, that means, Branch won't be able to deep link.

**Comment by dustinkerstein** [comment]
K, I will post over on the Oculus forums to see if they are planning on supported deep linked UX's in the future. Thanks.
