### ISSUE TITLE
Cannot retrieve universal link data

### ISSUE THREAD

**Issue by shirkan** [BranchMetrics/unity-branch-deep-linking-attribution#106]
Hello,
For some reason, Branch.getLatestReferringBranchUniversalObject() & Branch.getLatestReferringBranchLinkProperties() started returning empty data objects in the last few days. Printing the retrieved objects yields:
```
UniversalObject:
{"$canonical_identifier":"","$canonical_url":"","$og_title":"","$og_description":"","$og_image_url":"","$content_type":"","$publicly_indexable":"0","$exp_date":"0","$keywords":[],"metadata":{}}
LinkProperties:
{"~tags":[],"~feature":"","~alias":"","~channel":"","~stage":"","~duration":"0","control_params":{}}

```
This happens only on iOS, when app is installed. It doesn't matter if it runs in the BG or not, it always receives blank data.
On Init, I have this code which also parses blank data:

```
Branch.initSession(delegate (BranchUniversalObject obj, BranchLinkProperties props, string error) {
	if (error != null ) {
		Debug.Log("*************** BRANCH INIT ERROR: " + error);
	} else {
		CheckUniversalObject(obj);
	}
});
```
displayed debug message is:
```
callbackDictString: 

{"callbackId":"BranchCallbackId1","error":null,"params":{"linkProperties":{},"universalObject":{}}}
```

Some more details:
Branch Unity SDK 0.3.25, iOS version 10.3 & 11 latest, xcode 8.3 & xcode 9 latest, Unity version 5.6.1f1. 

Branch key is configured correctly and I update iOS wrapper as well.
Please help.

**Comment by antonargunov** [comment]
Hi, let me check

**Comment by shirkan** [comment]
Hi, is there something I can do to try tackling the issue meanwhile?

**Comment by antonargunov** [comment]
Hi @shirkan , check please entitlements in your xcode project.
entitlements should contain "associated domains" keys.

**Comment by shirkan** [comment]
The entitlements are configured just fine...
![image](https://user-images.githubusercontent.com/860107/32432147-1a31a506-c2df-11e7-96a6-ee9eeb48443d.png)

**Comment by antonargunov** [comment]
@shirkan , please, do quick test with our testbed and try your old links and new link generated from testbed

**Comment by shirkan** [comment]
Testbed seems to work fine on iOS with my IDs & keys

**Comment by antonargunov** [comment]
did you add other plugins into your project?
it can be several app controllers, try to find "IMPL_APP_CONTROLLER_SUBCLASS"

**Comment by shirkan** [comment]
I found it on UnityAppController.h and on AppsFlyerAppController.m, but it used to run ok with Appsflyer

**Comment by antonargunov** [comment]
Look at https://github.com/BranchMetrics/unity-branch-deep-linking#several-impl_app_controller_subclass

As I understand AppsFlyerAppController.m has IMPL_APP_CONTROLLER_SUBCLASS
Our BranchAppController.mm has IMPL_APP_CONTROLLER_SUBCLASS too

you should to merge that files and keep only one IMPL_APP_CONTROLLER_SUBCLASS

**Comment by shirkan** [comment]
I've tried this solution, but it only works after I merge both file into one *and* remove 

> IMPL_APP_CONTROLLER_SUBCLASS(AppsFlyerAppController)

This will cause AppsFlyer not to function correctly. Is there a solution for this? Can't Branch.io & Appsflyer work simultanously? 
Thanks.

**Comment by antonargunov** [comment]
> This will cause AppsFlyer not to function correctly

That means, you merged files incorrectly and cut some methods/calls for AppsFlyer.

This is an example for cardboard sdk:
https://github.com/BranchMetrics/unity-branch-deep-linking/tree/master/ThirdPartySolutions/CardboardSDK_ios

**Comment by shirkan** [comment]
Got it, works good.
Thanks for your dedicated help! :)
