### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by shirkan** [BranchMetrics/unity-branch-deep-linking-attribution#107]
On Editor/EntitlementsPostProcess.cs, line 39, change:
`        
FileUtil.CopyFileOrDirectory(src, dst);
`

To:
```
if (!System.IO.File.Exists(dst)) {
	FileUtil.CopyFileOrDirectory(src, dst);
}        
```

In local building, this causes an error if entitlements file already exists. You may also want to override it instead.
Thanks.

**Comment by antonargunov** [comment]
@shirkan , don't understand, as I know we don't have EntitlementsPostProcess.cs

**Comment by shirkan** [comment]
OOOPS! sorry, wrong repository 😄
