### ISSUE TITLE
iOS Share Sheet link sometimes includes Branch Live Key

### ISSUE THREAD

**Issue by dustinkerstein** [BranchMetrics/unity-branch-deep-linking-attribution#108]
Testing on version 0.3.20 and iOS 11, when sharing a link via Branch.shareLink() usually it looks like: https://customdomain.com/CD0P/xyz but sometimes the link doesn't get shortened correctly with my custom domain and includes my Branch Live Key. I've not yet determined how to consistently replicate this as it seems like it might depend on a callback from Branch.io web services. When this does happen, the link still works, but it's an ugly mess and I am concerned that it's a bit of a security risk to have my live key exposed publicly like that.

Has anyone seen this before? Is it possibly fixed in newer versions of the SDK?

**Comment by antonargunov** [comment]
Hi @dustinkerstein , try new version.
You can download new version from our github:
https://github.com/BranchMetrics/unity-branch-deep-linking

Later today we will add new version on our s3.

**Comment by dustinkerstein** [comment]
@antonargunov ok I will definitely try that. Do you happen to know if there were any specific changes that could affect this behavior?

**Comment by antonargunov** [comment]
@dustinkerstein , look at changes in ios sdk v0.19.0:
https://github.com/BranchMetrics/ios-branch-deep-linking/blob/master/ChangeLog.md

This changes added in Unity SDK v0.3.23

**Comment by dustinkerstein** [comment]
Ah, the "duplicate URL" issue. Do you think that's the same issue? It wasn't just a duplicate of https://customdomain.com/CD0P/xyz, but instead included an extremely long URL (and maybe also was duplicated, though I can't remember - I only saw it happen once during testing).

**Comment by antonargunov** [comment]
See below in change log, there are several changes for link generation.
I think you just need to update SDK :)

**Comment by dustinkerstein** [comment]
K, will do. Thanks!
