### ISSUE TITLE
java.lang.ClassCastException: io.branch.referral.BranchApp cannot be cast to android.app.Activity

### ISSUE THREAD

**Issue by shirkan** [BranchMetrics/unity-branch-deep-linking-attribution#110]
Hi,
I need to enable the multidex option in my Unity Android build and also support it for Android 4.4.4 and below. This is why on my main AndroidManifest.xml the application tag is:

`<application android:icon="@drawable/app_icon" android:label="@string/app_name" android:name="android.support.multidex.MultiDexApplication">`

I've set up branch for the main activity in AndroidManifest.xml:
```

<activity android:name="io.branch.unity.BranchUnityActivity" android:launchMode="singleTask" android:label="@string/app_name" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>

      <intent-filter>
        <data android:host="open" android:scheme="*****" />
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
      </intent-filter>

      <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="https" android:host="*****.app.link" />
        <data android:scheme="https" android:host="*****-alternate.app.link" />
      </intent-filter>

      <meta-data android:name="android.app.lib_name" android:value="unity" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
    </activity>
```

but I keep getting this error.
When I set "io.branch.referral.BranchApp" as the android:name on "application" tag, it works fine on Android versions >4.4.4, but crashes on Android versions <=4.4.4.
Please help, thanks.

**Comment by antonargunov** [comment]
Hi, min android sdk version for branch is 15.
Check your other plugins.

**Comment by shirkan** [comment]
Hi,
In the build.gradle file I've set "minSdkVersion 15". Android 4.4.4 is sdk 19 so there should be no problem with that.

**Comment by antonargunov** [comment]
Trouble can be with:
1) another plugin, because another plugin can require minSDkVersion higher than 15
2) multidex feature, because when you use sdk version 20 or less, you should add multidex support library: https://developer.android.com/studio/build/multidex.html

**Comment by shirkan** [comment]
Hi again,
1. Actually in Branch/Android/AndroidManifest.xml the minimal SDK version is:
`<uses-sdk android:minSdkVersion="16" />`
I checked all other minSDKVersion properties in other manifests, they all state a lower version than 16 and also 15. I changed the minSDKVersion in the main manifest to 16 as well, and so in the build.gradle file. I still have the same error.
2. I already stated before I've added all necessary build properties to the build.gradle file to support multidex below SDK version 20.
**BTW**, part of enabling multidex support for sdk version below 20 is to replace the application main class:
```
<application
            android:name="android.support.multidex.MultiDexApplication" >
        ...
    </application>
```
So I cannot use "io.branch.referral.BranchApp" as the main class.
This makes the app works fine except catching the branch universal links. In other words, I couldn't retrieve branch universal links data without declaring "io.branch.referral.BranchApp" as the main class.

This is how the main build.gradle file looks now:

```
buildscript {
	repositories {
		jcenter()
	}

	dependencies {
        classpath 'com.android.tools.build:gradle:2.2.3'
	}
}

allprojects {
   repositories {
      flatDir {
        dirs 'libs'
      }
   }
}

apply plugin: 'com.android.application'

dependencies {
    compile 'com.android.support:multidex:1.0.1'
	compile fileTree(dir: 'libs', include: ['*.jar'])
	compile(name: 'AmazonAppStore', ext:'aar')
	compile(name: 'CloudMoolah', ext:'aar')
	compile(name: 'GoogleAIDL', ext:'aar')
	compile(name: 'GooglePlay', ext:'aar')
	compile(name: 'SamsungApps', ext:'aar')
	compile(name: 'ShortcutBadger-1.1.5', ext:'aar')
	compile(name: 'UnityAds', ext:'aar')
	compile(name: 'animated-vector-drawable-25.0.0', ext:'aar')
	compile(name: 'appcompat-v7-25.0.0', ext:'aar')
	compile(name: 'cardview-v7-23.4.0', ext:'aar')
	compile(name: 'common', ext:'aar')
	compile(name: 'customtabs-23.4.0', ext:'aar')
	compile(name: 'facebook-android-sdk-4.23.0', ext:'aar')
	compile(name: 'facebook-android-wrapper-7.10.0', ext:'aar')
	compile(name: 'onesignal-unity', ext:'aar')
	compile(name: 'play-services-ads-9.8.0', ext:'aar')
	compile(name: 'play-services-ads-lite-9.8.0', ext:'aar')
	compile(name: 'play-services-base-9.8.0', ext:'aar')
	compile(name: 'play-services-basement-9.8.0', ext:'aar')
	compile(name: 'play-services-clearcut-9.8.0', ext:'aar')
	compile(name: 'play-services-gass-9.8.0', ext:'aar')
	compile(name: 'play-services-gcm-9.8.0', ext:'aar')
	compile(name: 'play-services-iid-9.8.0', ext:'aar')
	compile(name: 'play-services-location-9.8.0', ext:'aar')
	compile(name: 'play-services-tasks-9.8.0', ext:'aar')
	compile(name: 'support-compat-25.0.0', ext:'aar')
	compile(name: 'support-core-ui-25.0.0', ext:'aar')
	compile(name: 'support-core-utils-25.0.0', ext:'aar')
	compile(name: 'support-fragment-25.0.0', ext:'aar')
	compile(name: 'support-media-compat-25.0.0', ext:'aar')
	compile(name: 'support-v4-25.0.0', ext:'aar')
	compile(name: 'support-vector-drawable-25.0.0', ext:'aar')
	compile project(':AdMob')
	compile project(':ChartboostSDK')
	compile project(':GoogleMobileAdsPlugin')
	compile project(':Heyzap')
	compile project(':OneSignalConfig')
	compile project(':Tapdaq')
	compile project(':UTNotifications')
	compile project(':Vungle_lib')
	compile project(':unity-android-resources')
}

android {
	compileSdkVersion 24
	buildToolsVersion '24.0.3'

	defaultConfig {
		targetSdkVersion 24
		applicationId '***.***.***'
        multiDexEnabled true
        minSdkVersion 16
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

	lintOptions {
		abortOnError false
	}
	signingConfigs { release {
		storeFile file('***')
		storePassword '***'
		keyAlias '***'
		keyPassword '***'
	} }

	buildTypes {
		debug {
			jniDebuggable true
		}
		release {
			// Set minifyEnabled to true if you want to run ProGuard on your project
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-unity.txt'
			signingConfig signingConfigs.release
		}
	}

}

```

**Comment by antonargunov** [comment]
@shirkan , you just need make custom android plugin where you will mix branch and multidexapp.

Look at our example for solving conflict between Fabric library and Branch library.

Source code:
https://github.com/BranchMetrics/unity-branch-deep-linking/tree/master/AndroidThirdParty

How to use your custom library:
https://github.com/BranchMetrics/unity-branch-deep-linking/tree/master/ThirdPartySolutions


Main idea is:
- you extend your custom class with multidexapp
- you add methods for initialization of Branch
- you make your own library with custom app and/or custom activity
- you set your custom names into "android:name" params

**Comment by shirkan** [comment]
Got it, thanks.
