### ISSUE TITLE
401 Unauthorized when preparing Fabric

### ISSUE THREAD

**Issue by rafaelbenavent** [BranchMetrics/unity-branch-deep-linking-attribution#115]
In Fabric for Unity, when I click "Prepare Fabric" from the "Fabric" submenu from the menu bar, it launches a small popup window titled "Please select your organization" where I get a 401 unauthorized error when trying to fetch my account.

**Comment by antonargunov** [comment]
Hello, I think you should to ask Fabric team about this issue.

**Comment by csalmi-branch** [comment]
I am closing this issue due to the age and because it is likely a Fabric issue. If you are still experiencing an issue, [please contact our support team](https://support.branch.io/support/tickets/new) or open a new github issue.
