### ISSUE TITLE
Branch api key should be read from the info.plist

### ISSUE THREAD

**Issue by wpinaud** [BranchMetrics/unity-branch-deep-linking-attribution#118]
https://github.com/BranchMetrics/unity-branch-deep-linking/blob/2a85adbce331e1f683b3ad7dcadbae1c9dde8125/BranchUnityTestBed/Assets/Plugins/Branch/iOS/BranchiOSWrapper.mm#L8

When the application is hardclosed, then opened from a deeplink this hardcoded key is used by default to setup the SDK.

During this session, all deeplinks won't return any parameters (branch key incorrect).

This key should be read from the info.plist to work in any situation without having to rely on Unity to set the key.

```
static NSString *_branchKey = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"BranchKey"];
```

**Comment by antonargunov** [comment]
@wpinaud , after you set or re-set your key, uri, link scheme in branch prefab, you need to tap button "update ios wrapper" to set valid key into this parameter.

**Comment by scholargifer** [comment]
please clone our team's backend repository and then add your api-url in Keys.plist

I already cloned the backened repo. How can I find my api-url?

**Comment by antonargunov** [comment]
@scholargifer sorry, don't understand
