### ISSUE TITLE
Multiple instances of the Branch object in some cases.

### ISSUE THREAD

**Issue by sholev** [BranchMetrics/unity-branch-deep-linking-attribution#126]
The code handling the branch instance might fail to find if there is an existing instance already and this will cause duplication of the object:

    public void Awake() {
        var olderBranch = FindObjectOfType<Branch>();

        if (olderBranch != null && olderBranch != this) {
            // someone's already here!
            Destroy(gameObject);
            return;
        }

        name = "Branch";
        DontDestroyOnLoad(gameObject);

        if (BranchData.Instance.testMode) {
            _setBranchKey(BranchData.Instance.testBranchKey);
        }
        else {
            _setBranchKey(BranchData.Instance.liveBranchKey);
        }
    }

The problem here is that at the moment of execution of the **FindObjectOfType<Branch>()** method, if there is more than one instance of the object, which has the **Branch** script as a component, it is not guaranteed that the instance returned by the method will not be the same as the current instance. Therefore the **olderBranch != this** check will be **False** and we will end up with more than one instance of the object. The reason this is might happen is because the **FindObjectOfType** method doesn't guarantee it will find the objects of this type in any particular order.

A possible fix for this would be:

    public void Awake() {
        var branches = FindObjectsOfType<Branch>();

        if (branches != null && branches.Length > 1) {
            // someone's already here!
            Destroy(gameObject);
            return;
        }

        name = "Branch";
        DontDestroyOnLoad(gameObject);

        if (BranchData.Instance.testMode) {
            _setBranchKey(BranchData.Instance.testBranchKey);
        }
        else {
            _setBranchKey(BranchData.Instance.liveBranchKey);
        }
    }

**Comment by antonargunov** [comment]
Hi @sholev , thanks for your report.
We will fix this in the next release.

**Comment by csalmi-branch** [comment]
@antonargunov did you include a fix for this in a recent release?
