### ISSUE TITLE
Branch link breaks on the second time through iOS 10

### ISSUE THREAD

**Issue by Philip2990** [BranchMetrics/unity-branch-deep-linking-attribution#130]
I’m having an issue with using a deep link on iOS. We are using it to link back to our app after making a purchase on PayPal. It is working great the first time through but if you try to use it again it goes to the deep view and takes the user to the app store. It works again if you close the app completely and reopen it but again just the first time through. Also we found out through testing that it seems to only be an issue on iOS 10 or lower. When we tried it on an iOS 11 device it worked multiple times through the process.

Here is the log when I'm running through the process twice:

[DailyBibleJigsaw_logs.txt](https://github.com/BranchMetrics/unity-branch-deep-linking/files/2098318/DailyBibleJigsaw_logs.txt)

**Comment by antonargunov** [comment]
@Philip2990 
Write please Branch SDK version (you can find the version string in Branch.cs)

**Comment by Philip2990** [comment]
It's using sdk version 0.4.8.

**Comment by Philip2990** [comment]
Here is a video that shows the process shown in the logs.

https://youtu.be/diPQCcaCqRA

**Comment by antonargunov** [comment]
thanks, let me check

**Comment by Sarkar** [comment]
@Philip2990 thanks for reaching out. Do you mind sending this information to integrations@branch.io? It looks like you're testing on an iPad using iOS 10, can you also pass along the link you used, and your app ID? We'll get this straightened out, as this is most likely a linking issue instead of unity, but we can debug.

**Comment by Philip2990** [comment]
@Sarkar I reached out to them first and walked through the issue with them. They asked me to post it here.

**Comment by Philip2990** [comment]
Is there any update with this issue?

**Comment by Sarkar** [comment]
@Philip2990, the iOS team is looking into this now.

**Comment by csalmi-branch** [comment]
@Philip2990 are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
