### ISSUE TITLE
Upgrade to Unity 2018 causing 3x Branch compile errors

### ISSUE THREAD

**Issue by radbargames** [BranchMetrics/unity-branch-deep-linking-attribution#131]
BUG:
After upgrading to Unity 2018 the Branch SDK gives compile errors:

Assets/Branch/Editor/BranchPostProcessBuild.cs(153,13): error CS1061: Type `UnityEditor.iOS.Xcode.PBXProject' does not contain a definition for `HasFramework' and no extension method `HasFramework' of type `UnityEditor.iOS.Xcode.PBXProject' could be found. Are you missing an assembly reference?

To reproduce:
1. Install Unity 2018.1.f4
2. Create a brand-new project
3. Install the current Branch SDK
4. Open Build Settings, select iOS and Switch Platform

Result:
4 compile errors as above, which were not present in Unity 2017

Looks like you may just need a UNITY_2017 || UNITY_2018 instead of just UNITY_2017?

**Comment by antonargunov** [comment]
@radbargames , change please row 133 in BranchPostProcessBuild.cs:
change UNITY_2017 to UNITY_2017_1_OR_NEWER

**Comment by dgoodine** [comment]
This worked for me when I had the same problem installing today.
