### ISSUE TITLE
Clean project error in Editor

### ISSUE THREAD

**Issue by novavision** [BranchMetrics/unity-branch-deep-linking-attribution#134]
Just after importing package to my project I get this error in Editor
Assets/Branch/MiniJSON.cs(120,12): error CS1674: `BranchThirdParty_MiniJSON.Json.Parser': type used in a using statement must be implicitly convertible to `System.IDisposable'

I am using .NET 4.x, Unity 2018.2.2f1

Can't do anything with that. What's the reason?

**Comment by antonargunov** [comment]
@novavision , it is strange, with Unity 2018.2.5f1 I don't have any issues. Let me check several things.

**Comment by novavision** [comment]
oh... the only what I left in a project is my custom Utils library with IDisposable interface there.. conflict been caused because of that..
Sorry, ticket can be closed
