### ISSUE TITLE
Branch Android SDK with com.android.support:multidex:1.0.3

### ISSUE THREAD

**Issue by galeksic90** [BranchMetrics/unity-branch-deep-linking-attribution#139]
Hello,

We needed to change application android:name in order to setup Branch SDK, but we need also to use multidex, is there a way to run both of them?

**Comment by antonargunov** [comment]
Hello, sorry, don't understand why you can't use multidex.

**Comment by goranships** [comment]
Hi Anton,

In order to use multidex on android there should be application android:name set to android.support.multidex.MultiDexApplication, but branch requires it to be changed to io.branch.unity.BranchUnityApp.

**Comment by antonargunov** [comment]
Hi @hivearts , 
https://appmediation.com/unity-enable-multidex/
you need to change class name only when your minimum API is 20 or lower.

**Comment by goranships** [comment]
Hi @antonargunov 

Yes, thats true, but we would like to support devices below API 20 which is android 4.4.4...

**Comment by antonargunov** [comment]
Hi @hivearts ,
let me check how we can do that

**Comment by antonargunov** [comment]
@hivearts 
try this solution:
https://www.dropbox.com/s/k1ehpb1cs6vt6ti/MultiDexSupport.zip?dl=0

1) change current library with library from archive
2) in project settings select "custom gradle template"
3) change your gradle file in accordance with example from archive

try and if all will work for you - I will add this solution in Unity3d SDK

**Comment by goranships** [comment]
@antonargunov 

Thanks, ill try it today.

Is it possible to implement com.android.support:multidex:1.0.3 since we are using newer gradle and unity version which is required i think?

**Comment by goranships** [comment]
@antonargunov 

I just have tested your wrapper on old android device, and it seems to work with 1.0.1 multidex! I will confirm you in a few days, so you can update Unity3d SDK.

Thank you!

**Comment by antonargunov** [comment]
@hivearts 
ok, thank you

**Comment by antonargunov** [comment]
@hivearts do you have any news?

**Comment by goranships** [comment]
@antonargunov Hey, yes it works. We have seen on analytics there is a guy running our app on android 4.1.2. Ill let you know if we found any problem.

**Comment by dmarqs** [comment]
Hi, so what's the final solution is? Should I replace android:name from multidex to branch or not? What about the files in dropbox, it's already implemented in Unity SDK by this day (Jan/2020)?

thanks everyone, I'm days in this already.

**Comment by antonargunov** [comment]
@dmarqs https://github.com/BranchMetrics/unity-branch-deep-linking-attribution#android-multidex-support

**Comment by dmarqs** [comment]
Hi @antonargunov, unfortunately it didn't worked for me. Do you mind to take a look at my build and manifest? I'm not used to android code, don't know if I didn't mix thing right with my already custom build.gradle https://drive.google.com/open?id=1XvEk8BH7Orfr9IU0omKPpUd43jbidRtJ

**Comment by antonargunov** [comment]
@dmarqs you can find example of manifest and gradle file in Plugins/Branch/Android folder
