### ISSUE TITLE
Broken link to changelog.

### ISSUE THREAD

**Issue by JimmyDeemo** [BranchMetrics/unity-branch-deep-linking-attribution#141]
The main read me has the following link to change logs; https://github.com/BranchMetrics/unity-branch-deep-linking/blob/master/ChangeLog.md.

This 404's, and change logs cannot be viewed.

**Comment by antonargunov** [comment]
Hi, try this link please:
https://github.com/BranchMetrics/unity-branch-deep-linking/blob/master/Changelog.md

**Comment by JimmyDeemo** [comment]
Yes, this link works. Thanks.
