### ISSUE TITLE
Branch.shareLink callback is not always called on Android

### ISSUE THREAD

**Issue by dshetty-branch** [BranchMetrics/unity-branch-deep-linking-attribution#144]
If no share option is selected on the share dialog when Branch.shareLink is called the callback is never called. 
Expected behaviour is that the callback would be called with a success, but no parameters (as nothing was chosen), this is what happens on iOS. The behaviour should be consistent and at the very least tell when the process has completed.

**Comment by csalmi-branch** [comment]
The fix for this has been included in v0.5.5. Please let us know if you are encountering the issue still, or any other issues.
