### ISSUE TITLE
Unity Freeze on Deeplink

### ISSUE THREAD

**Issue by fahall** [BranchMetrics/unity-branch-deep-linking-attribution#145]
@antonargunov 

I mentioned in [this ticket](https://github.com/BranchMetrics/unity-branch-deep-linking/issues/87) that I successfully used Unity Cloud Build with xCode 10.1 & Unity version 2017.2.1f1 to build our app with the latest Branch SDK (0.5.4).

Since upgrading, I notice that our app freezes when entering through a deeplink. This does not happen when we use 0.4.5. I've confirmed that the only change between the working and non-working versions is the upgrade to 0.5.4. 

Any thoughts as to what might be causing this? Additional information I can provide you?

**Comment by antonargunov** [comment]
@fahall what does mean "freezes"? app does not work at all? or you need to wait several seconds/minutes?

**Comment by antonargunov** [comment]
@fahall can you reproduce this issue with empty app + Branch SDK? I just need a "project" where I will be able to reproduce this issue too.

do you use method `Branch.setTrackingDisabled(bool value)`?

**Comment by csalmi-branch** [comment]
@fahall are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
