### ISSUE TITLE
Proguard settings

### ISSUE THREAD

**Issue by xtrecoolx** [BranchMetrics/unity-branch-deep-linking-attribution#146]
Can you please share your proguard settings for this package ? I've just installed it and it does not build when proguard is on.
Thank you.

**Comment by antonargunov** [comment]
@xtrecoolx proguard settings for
1) Branch-3.0.3_core.jar
- no settings

2) BranchAndroidWrapper.jar
- proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
- proguard-rules.pro is empty

**Comment by xtrecoolx** [comment]
@antonargunov I am sorry I did not quite get it. I mean what should I type in the settings text file.
Maybe something like:
`# Keep all classes in Unity Services package
-keep class com.unity3d.services.** {
   *;
}`

**Comment by antonargunov** [comment]
@xtrecoolx how did you enable proguard?

**Comment by xtrecoolx** [comment]
Well in my Unity game I have proguard enabled at the build settings. I wanted to integrate Branch.io SDK for deep links but the build fails due to proguard. The proguard settings are enabled at the player settings in Unity if that's what you are looking for and it reads proguard-user.txt file for settings.

**Comment by antonargunov** [comment]
ok, understood, let me check

**Comment by antonargunov** [comment]
@xtrecoolx I enabled proguard in our testbed, all works.

> it does not build when proguard is on.

- does it build when proguard is off?
- can you send me error log?
- which version of Unity3d do you use?
- can you reproduce this in empty project + Branch SDK?

**Comment by xtrecoolx** [comment]
@antonargunov Here are my answers:

- Well I did try to build it without proguard and it failed. It looks like its conflicting with Firebase SDK.
I get errors like:

`UnityEditor.BuildPlayerWindow+BuildMethodException: 2 errors
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForRelease'.`

`/mygame/Temp/gradleOut/libs/Branch-3.0.3_core.jar: D8: Type `com.google.firebase.appindexing.FirebaseUserActions` was not found, it is required for default or static interface methods desugaring of `void io.branch.indexing.AppIndexingHelper$1.run()``

- I am running Unity 2018.3.0f2 on MacOS. The project contains Facebook SDK, Firebase SDK (Firebase Auth, Analytics, DynamicLinks, Storage, Messaging), Admob and Admob Mediation SDKs.

**Comment by xtrecoolx** [comment]
I also see errors such as
`Note: io.branch.indexing.AppIndexingHelper: can't find dynamically referenced class com.google.android.gms.appindexing.Thing
Note: io.branch.indexing.AppIndexingHelper: can't find dynamically referenced class com.google.android.gms.appindexing.Thing$Builder
Note: io.branch.indexing.AppIndexingHelper: can't find dynamically referenced class com.google.android.gms.appindexing.Action
Note: io.branch.indexing.AppIndexingHelper: can't find dynamically referenced class com.google.android.gms.appindexing.Action$Builder
Note: io.branch.indexing.AppIndexingHelper: can't find dynamically referenced class com.google.android.gms.appindexing.AppIndex
Note: io.branch.indexing.AppIndexingHelper: can't find dynamically referenced class com.google.android.gms.appindexing.AppIndexApi`

**Comment by antonargunov** [comment]
@xtrecoolx try to add in plugins/android folder this .arr file:
https://mvnrepository.com/artifact/com.google.firebase/firebase-appindexing/17.1.0

**Comment by csalmi-branch** [comment]
@xtrecoolx Are you still experiencing this issue?

**Comment by csalmi-branch** [comment]
Due to the age and inactivity of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!
