### ISSUE TITLE
Branch CallBack Function cannot get return link from web

### ISSUE THREAD

**Issue by junaidsaleem** [BranchMetrics/unity-branch-deep-linking-attribution#152]
I want to get redirect link with code. our server returns deep link with code. like (https://axnc7.app.link/HMCcbtAC1W?code=asdfasdf) but when I'm using a callback function and Branch.getShortURL there is only 1 link, not code. how I get the code which returns our server.

**Comment by junaidsaleem** [comment]
This is my Code wich is in CallbackWithBranchUniversalObject function

BranchUniversalObject obj = Branch.getLatestReferringBranchUniversalObject();
            BranchLinkProperties link = Branch.getLatestReferringBranchLinkProperties();
            Branch.getShortURL(obj, link, (url, error1) => {
                if (error1 != null)
                {
                    Debug.LogError("Branch.getShortURL failed: " + error);
                }
                else
                {
                    Debug.Log("Branch.getShortURL shared params: " + url);
                    LaunchFromUrl(url);
                    isLogin = true;
                }

**Comment by antonargunov** [comment]
@junaidsaleem can you explain what you want to do at all?

**Comment by csalmi-branch** [comment]
@junaidsaleem are you still experiencing an issue? If so, could you provide more details on what you are trying to do, as well as what Unity/SDK versions you are using?

**Comment by antonargunov** [comment]
@junaidsaleem we have uploaded new version with support of Unity 2019.x

if you will have any trouble - create new ticket please.
