### ISSUE TITLE
Link property alias not being added to custom link generated

### ISSUE THREAD

**Issue by hk0129** [BranchMetrics/unity-branch-deep-linking-attribution#160]
Hi, Getting a short URL with Unity doesn't create a link with provided alias. Instead it always generates a different link even if an alias is provided.

` Sample Code to recreate issue

            BranchUniversalObject universalObject = new BranchUniversalObject();
            universalObject.canonicalIdentifier = "id12345";
            universalObject.canonicalUrl = "https://branch.io";
            universalObject.title = "id12345 title";
            universalObject.contentDescription = "My awesome piece of content!";
            universalObject.metadata.AddCustomMetadata("foo", "bar");
           // register a view to add to the index
            Branch.registerView(universalObject);
            BranchLinkProperties linkProperties = new BranchLinkProperties();
            linkProperties.alias = "customaliaslink
            linkProperties.tags.Add("tag1");
            linkProperties.feature = "sharing";

            Branch.getShortURL(universalObject, linkProperties, (url, error) =>
            {
                if (error != null)
                {
                    Debug.LogError("Branch.getShortURL failed: " + error);
                }
                else
                {
                    Debug.Log("Branch.getShortURL url: " + url);
                }
            });
`

I've identified the cause for this issue and will be making a PR asap.
Thank you.

**Comment by antonargunov** [comment]
@hdjay0129 thanks for the report!
we will add the fix in Unity SDK asap.
