### ISSUE TITLE
BranchData.asset was submit using Unity 2019.2.0f1 and cannot be read by Unity 2018 versions

### ISSUE THREAD

**Issue by yanivshaked** [BranchMetrics/unity-branch-deep-linking-attribution#163]
The [BranchData.asset](https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/blob/master/BranchUnityTestBed/Assets/Branch/Resources/BranchData.asset) file was submit using Unity 2019.2.0f1 and cannot be deserialized by Unity 2018 versions.
Unity 2018.4 is the latest LTS version - [Long Term Support](https://unity3d.com/unity/qa/lts-releases) which means it is a latest stable stream of Unity (with extended support).

Please submit this file using a more compatible version of Unity (2018).

**Comment by RoiLaredo** [comment]
+1
please fix ASAP.

**Comment by csalmi-branch** [comment]
We are currently working on providing a compatible file.

**Comment by antonargunov** [comment]
Fixed, try this link (from repo):
https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/blob/master/BranchUnityWrapper.unitypackage

We will update our S3 link soon.

**Comment by yanivshaked** [comment]
Thanks for the updated package, I will update soon.

**Comment by antonargunov** [comment]
@yanivshaked  write then about result please

**Comment by yanivshaked** [comment]
Sure, I will report back

**Comment by antonargunov** [comment]
btw, we updated our S3:
https://s3-us-west-1.amazonaws.com/branchhost/BranchUnityWrapper.unitypackage

**Comment by yanivshaked** [comment]
Sorry, but it looks like something is broken. After double clicking the unitypackage file, Unity shows some processing, but when its over nothing comes up. I tried restarting my Unity, same result.

**Comment by antonargunov** [comment]
I tried in empty project (Unity3d 2018.2.x), al is ok.

which version of Unity do you use?
can you try to delete last version of SDK and try again?
can you try add SDK in new empty plugin?

**Comment by yanivshaked** [comment]
I'm using 2018.4.4f1. I will try deleting first.

**Comment by yanivshaked** [comment]
Importing issue is solved after I reboot my machine. However, I am still getting the following error after importing:

Failed to load 'C:/dev/nogame/git/unity3rd/NoGame/Assets/Branch/Resources/BranchData.asset' because it was serialized with a newer version of Unity. (Has a higher SerializedFile version)

If you look at the BranchData.asset file header, you can still see Unity 2019.2.0f1 signature:

<img width="442" alt="2019-11-02_00h00_41" src="https://user-images.githubusercontent.com/13107481/68059092-dd3cf680-fd03-11e9-8b27-8cf4a60e4b00.png">

Please help....

**Comment by antonargunov** [comment]
@yanivshaked  try this package:
https://www.dropbox.com/s/r5ej9h11qk5cm40/BranchUnityWrapper.unitypackage?dl=0

**Comment by yanivshaked** [comment]
Looks like problem is resolved.

**Comment by antonargunov** [comment]
Unity package updated, you can upload from the repo, S3 will be updated soon.
