### ISSUE TITLE
Something's wrong with the unitypackage link on the docs.branch.io website 

### ISSUE THREAD

**Issue by James-deWitt** [BranchMetrics/unity-branch-deep-linking-attribution#168]
The .unitypackage file on the branch documentation site https://docs.branch.io/apps/unity/ (download link https://s3-us-west-1.amazonaws.com/branchhost/BranchUnityWrapper.unitypackage) cannot be imported into unity. It gives the error:

> Failed to import package with error: Couldn't decompress package

The one from the latest github release seems to be fine

**Comment by antonargunov** [comment]
@James-deWitt thanks for report,
try to download the package from GitHub:
https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/blob/master/BranchUnityWrapper.unitypackage

**Comment by antonargunov** [comment]
@James-deWitt we have uploaded new version with support of Unity 2019.x

if you will have any troubles - create please new ticket.
