### ISSUE TITLE
Install referrer API

### ISSUE THREAD

**Issue by JimmyDeemo** [BranchMetrics/unity-branch-deep-linking-attribution#171]
When installing version 0.5.15 of the SDK I noticed that the AndroidManifest.xml file included the following element;

```
<!-- Add this for Branch for install referrer tracking-->
<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
  <intent-filter>
    <action android:name="com.android.vending.INSTALL_REFERRER" />
  </intent-filter>
</receiver>
```

This intent is to be deprecated at the end of February 2020; https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html.

Please can you tell me if the current Unity SDK implements the Install Referrer API (https://developer.android.com/google/play/installreferrer/library)? If not, is there a timeline for it's introduction into the SDK? Do we need to do anything such as fowarding data from our own API implementation (similar to what we had to do when multiple sources required the referrer intent data).

**Comment by antonargunov** [comment]
@JimmyDeemo current Unity SDK does not implement this feature. I will discuss this with android sdk developers about how to implement this functional in Unity SDK and will answer you asap.

**Comment by JimmyDeemo** [comment]
Thanks @antonargunov I will keep an eye on this ticket. Quick turnaround would be appreciated given that we will need to QA and release version of our app prior to the deadline.

**Comment by antonargunov** [comment]
@JimmyDeemo I discussed that with android developers. This feature is present in current Branch android library, that means this feature works in Unity too.

You need:
or) add in your_own_gradle_file.gradle 
```
dependencies {
    ...
    implementation 'com.android.installreferrer:installreferrer:1.1'
}
```

or) put referrer library in Plugins/Android

and) delete 

```
<!-- Add this for Branch for install referrer tracking-->
<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
  <intent-filter>
    <action android:name="com.android.vending.INSTALL_REFERRER" />
  </intent-filter>
</receiver>
```

**Comment by JimmyDeemo** [comment]
Thanks for the information @antonargunov, we will update the SDK and do as suggested.

**Comment by antonargunov** [comment]
@JimmyDeemo on Friday or on Monday we will have new version of Unity SDK, if you can wait for new version - wait please
