### ISSUE TITLE
Support for Unity 2019.3

### ISSUE THREAD

**Issue by NumaNumaNuma** [BranchMetrics/unity-branch-deep-linking-attribution#176]
Hi, 

Looks like the latest SDK doesn't support Unity 2019.3 (still using old XCode api), is there a plan to update? Or am I missing something?

**Comment by antonargunov** [comment]
@NumaNumaNuma it will be in the next version

**Comment by NumaNumaNuma** [comment]
Awesome thanks!

**Comment by antonargunov** [comment]
@NumaNumaNuma new version will be available today later, before updating check please your packages, because some old packages can throw exceptions:
https://issuetracker.unity3d.com/issues/ios-build-and-run-fails-on-mac-for-ios

**Comment by antonargunov** [comment]
@NumaNumaNuma we have uploaded new version of SDK. Download and use it please.

**Comment by NumaNumaNuma** [comment]
That was quick :) Thanks!
