### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Mann1ng** [BranchMetrics/unity-branch-deep-linking-attribution#178]
Hello, firstly many thanks for your ongoing support for the Unity community.  

I am trying to build a Unity ARFoundation app to iOS (x64 only supported by ARKit) using Unity 2019.3.2 and seem to have run up against a linking issue when trying to build from XCode to iPhone in the Branch plugin. 

XCode error is:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CSSearchableItem", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_METACLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_METACLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_WKWebView", referenced from:
      objc-class-ref in BNCUserAgentCollector.o
  "_OBJC_CLASS_$_CTTelephonyNetworkInfo", referenced from:
      objc-class-ref in BNCTelephony.o
  "_OBJC_CLASS_$_CSSearchableIndex", referenced from:
      objc-class-ref in BranchCSSearchableItemAttributeSet.o
  "_OBJC_CLASS_$_CSSearchableItemAttributeSet", referenced from:
      _OBJC_CLASS_$_BranchCSSearchableItemAttributeSet in BranchCSSearchableItemAttributeSet.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any help very much appreciated. :)

**Comment by antonargunov** [comment]
@Mann1ng let me check

**Comment by antonargunov** [comment]
@Mann1ng I fixed this issue, you can download newest package from GitHub or you can wait for when we upload new package on S3.

**Comment by antonargunov** [comment]
We have uploaded newest version of SDK on S3. Use it please.
