### ISSUE TITLE
Support for iOS 15 and NativeLink

### ISSUE THREAD

**Issue by dustinkerstein** [BranchMetrics/unity-branch-deep-linking-attribution#196]
Does the current Unity SDK have the latest iOS updates to correctly support iOS 15 and NativeLink?

Thanks,
Dustin

**Comment by dustinkerstein** [comment]
It looks like the latest version of this Unity SDK only includes the iOS SDK 1.39.2, but per the email notification, iOS SDK v1.39.4 or higher is required. Can this be manually integrated?

**Comment by echo-branch** [comment]
@dustinkerstein 
The iOS SDK version should be pinned to the minor version, so it should auto update to 1.39.4.
https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/blob/master/BranchUnityTestBed/Assets/Branch/Editor/BranchDependencies.xml

You probably need to clear the cache to make sure the old version is removed first.

See the google documentation for details.
https://github.com/googlesamples/unity-jar-resolver

**Comment by dustinkerstein** [comment]
@echo-branch Thanks! I will give that a try.
