### ISSUE TITLE
Help needed: "Branch Error: Not implemented on this platform" after importing branch.io into our project.

### ISSUE THREAD

**Issue by FrankdenUijl** [BranchMetrics/unity-branch-deep-linking-attribution#199]
After importing this package into our project and playing (in the editor) the demo scene "BranchSDK_Demo" I got the following error:

![ThisIsDuringPlayMode](https://user-images.githubusercontent.com/8240783/171615516-16cac98a-6da2-4814-8821-a0e5f6eca4a2.png)

Where should I look to fix this issue? Any ideas?

Unity version: 2020.3.31f

**Comment by KarolVG** [comment]
Hey,  same problem here, did you figured it out?

**Comment by FrankdenUijl** [comment]
No, but I'm having contact with support@branch.io but they can't reproduce this issue. Maybe you can help by providing some additional information? What Unity version and how did you import branch.io into your project?

**Comment by FrankdenUijl** [comment]
[Branchio.zip](https://github.com/BranchMetrics/unity-branch-deep-linking-attribution/files/9038960/Branchio.zip)

I have reproduced it with an empty 2020.3.31f project, see the attached .zip file

**Comment by echo-branch** [comment]
@FrankdenUijl 
Thanks for the sample project, but I did not see the same error when run on my machine. I'm using Unity 2021.3.4f1 on macOS (m1).

Could you share your development and target platforms? Thank you.

**Comment by FrankdenUijl** [comment]
I'm on windows 11 with Unity version 2020.3.31f, same Unity version our development team works with. The error pop-up during play mode inside of the editor. 

> Edition	          Windows 11 Home
> Version	          21H2
> Installed on	  ‎10-‎3-‎2022
> OS build	  22000.739
> Experience	  Windows Feature Experience Pack 1000.22000.739.0

The platform is Android.

![image](https://user-images.githubusercontent.com/8240783/177522360-85d58722-f2e8-4c29-bb78-867b3a905b0a.png)

**Comment by KarolVG** [comment]
I am on windows 10 and my platform is android, still have that problem, also you've asked about how did i import branch, so I just simply import package normally, the latest version of course. :( I can't figure that error out, I have same error on iOS platform, it just doesnt work

**Comment by rob-gioia-branch** [comment]
Hi, this is Rob from Branch. If you play in the editor, this is expected. Since the Branch SDK relies on Native Components, this error will be displayed when you play in the editor. If you switch platforms to Android/iOS, create a build, and run it on device, you will not see that error in the Android logcat / XCode logs. 

**_TLDR: You can disregard getting this error in the editor. It is coming up because the Branch SDK relies on Native components, and will not occur when actually running a build on device._**
