### ISSUE TITLE
Too many ways to set and read the branch.io keys (updated, was: Please remove hardcoding the _branchKey in BranchiOSWrapper.mm)

### ISSUE THREAD

**Issue by derFunk** [BranchMetrics/unity-branch-deep-linking-attribution#20]
Hi,

handling the branch key(s) is not implemented straight forward in the branch.io Unity SDK.
I understand you wanted to make the Unity SDK as easy as possible for single Unity developers, but using the current SDK in a professional and fully automated build pipeline is very cumbersome.

The first main issue is: The key can be set by multiple methods and it's read from different sources:

**Setting the key:**
- Serialized via Unity Editor into the `BranchData` asset
- Replaced via the PostBuildScript directly within the `BranchiOSWrapper` (see below)
- Manually or via PostBuildScript in the `Info.plist` (there it's also possible to set it in two different ways: as a dict for both test and live keys OR as a single string key only).

**Reading the key:**
- Unity is reading the key in `Branch.cs`'s `Awake` method
  - A better practice would be to hand over the key in the initSession method, in order to be able to define it during runtime. Important for automated build pipelines. The key can also be stored in the `Branch.cs` MonoBehaviour directly, which would allow to get rid of the `BranchData.cs` class completely (you don't really need it).
  - **Also the `BranchData` class contains a static constructor, which is a bad practice and Unity 5.4 will throw compiler errors if you`re doing something like Resources.Load() or FindObject...() in it!**
- iOS / ObjC is reading the key from it's `BranchiOSWrapper.mm`'s `*_branchKey` variable
- iOS / ObjC is also reading it from the `Info.plist`

You see, that's pretty puzzling.

In my optimal world, I'd love to see branch.io integrating like this:

(C#/Unity pseudo code):

```
#if DEBUG
    Branch.initSession(Branch.TestKey, callback);
#else
    Branch.initSession(Branch.LiveKey, callback);
#endif
```

..where Branch.xxKey is serialized into the according script/scene and initSession is a fictitious method name.
This also allows for setting key values which come from a totally different origin (--> balancing data for games etc.)
### Please remove hardcoding the _branchKey in BranchiOSWrapper.mm

It should not be necessary to hardcode the branch key in `BranchiOSWrapper.mm` like this:

https://github.com/BranchMetrics/Unity-Deferred-Deep-Linking-SDK/blob/1a74f0c696a7effc0701c033654dd53e405d29b1/BranchUnityTestBed/Assets/Branch/Editor/BranchEditor.cs#L50

This adds a lot of overhead when having an automated build pipeline - we would have to replace the key in the `BranchiOSWrapper.mm` everytime we want to switch between `live` and `test` et cetera.

Especially because the branch keys (both test and live) are already stored in the Info.plist (according to https://dev.branch.io/getting-started/integration-testing/guide/ios/#specifying-both-test-and-live-keys-in-your-app) - you should read them from there and get completely rid of the changes made regarding setting/updating the branch key from within the Unity editor in 1a74f0c696a7effc0701c033654dd53e405d29b1.

**Comment by antonargunov** [comment]
Hi derFunk, 
thanks for the report!

We added hardcoded key to fix cold launch trouble, when key isn't initialised from Unity (sorry but we can't manage order of calls under Unity).

Initialisation of Unity Branch SDK is different than native iOS SDK because our plugin supports Android too, so we make Unity realisation without platform specific things (you don't need to keep keys in plist).

It will be very helpful if you will describe your auto-building and how we can change our Unity SDK to support your pipeline. If you can send us test project with auto-building then it will be great!

Nevertheless we will think how we can remove hardcoded key and I think we will change this in the next version of SDK.

**Comment by derFunk** [comment]
Hi Anton,

thanks again for the fast response (wow, it's Sunday! :) )

Short roundup about our pipeline:
Our automated build pipeline basically follows the convention that we want to be able to configure every plugin setting manually _and_ centrally.
That is because we're integrating more than 5 different plugins into almost every project/game, in average. We're totally avoiding PostBuildProcesses and stripping them out as soon as we see them, to be able to keep track what configuration and dependenvies every plugin needs. We also don't necessarily want to configure plugin keys in Editor Windows (but I understand this is comfortable for the average dev). _Configuration in code_ is just fine (which does not necessarily mean that everything is hardcoded, instead it's in different datastores which get loaded at runtime).
We don't want the plugins to just "do magic" without us knowing what exactly is happening (as this can lead to hard to resolve problems with the builds, and we need the builds to be deterministic).
To be deterministic, even the Xcode projects are generated completely new for every build (no Unity "Xcode append" etc).

All plugin configuration values are coming from external data stores (so called "balancing data" for example). Normally we're having at least 2 different accounts for every plugin, which we want to be able to switch at build time (because we're working with partners a lot which often give us access to the plugin backends only late in the project phase, and we have to be able to test early, that's where we're using our own accounts).

We do this by having a "build parameter" (e.g. a preprocessor define) which just tells the code at build time which configuration to load (our keys or the ones from our partners/publishers).

That's why it's important to have a very central point to configure the plugin keys _in code_.

Having a plugin which loads it's configuration via _"static constructor magic"_ or within the _`Awake`_ methods of Unity are making our life harder, as at the same time we don't want to change the plugin's code, as it makes plugin updates a pain (checking the diffs.., documenting what we changed.. et cetera ;) ).

Hope this all makes sense to you ;)

**Comment by antonargunov** [comment]
derFunk,
We will think how to make our plugin better, but we need time.
Sorry, but right now you need to use "hard way" to set keys :)
(May be light post-processing will help you?)

Nevertheless I added this issue to dev plan, thanks!

**Comment by antonargunov** [comment]
Added to dev plan.
