### ISSUE TITLE
Missing header files in Xcode

### ISSUE THREAD

**Issue by dylan-infinitus** [BranchMetrics/unity-branch-deep-linking-attribution#209]
### Describe the bug

I have a Unity app I am building for iOS.
I have imported the Branch Unity package.

Building for iOS requires opening the Unity build output folder in Xcode and archiving the project to upload to Apple Connect.

--

When opening in Xcode, the project is missing multiple header files.

This has been mentioned in a few other issues:

https://github.com/BranchMetrics/react-native-branch-deep-linking-attribution/issues/18
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/pull/670

However, I am still receiving the error from a Unity build output.

Has the Unity package been updated with the supposed fixes?

### Steps to reproduce

1. Import Unity package to a Unity project
2. Build for iOS
3. Open in Xcode
4. Attempt to Archive the project

### Expected behavior

The project should be archived correctly and available to upload to Apple Connect.

### SDK Version

SDK-1523

### Unity Version

2021.3.25f1

### Make and Model

Xcode

### OS

Xcode

**Comment by echo-branch** [comment]
@dylan-infinitus 
Those are very old tickets and unlikely to be the same issue you've run into. 

I suspect you opened the xcodeproj instead of the xcworkspace file. The xcodeproj excludes dependencies managed by Cocoapods, which includes the Branch SDK.

If you're familiar with Visual Studio, these are similar to the solution vs csproj files.

**Comment by dylan-infinitus** [comment]
@echo-branch 

Thanks for the reply! 

I did some research before and discovered the `xcodeproj` vs `xcworkspace` file opening issue. Although... Unity doesn't generate a `xcworkspace` file by default.

So should I perform some additional configuration steps alongside the Branch Unity package to get it working? I assumed the package would work just by importing it. 

I'll keep digging and update here if I find a solution.

**Comment by echo-branch** [comment]
@dylan-infinitus 

Interesting. So for my test project the xcworkspace is automatically generated on build. Maybe something went wrong when trying to resolve the dependencies. 

Check the settings under `Assests -> External Dependency Manager -> iOS Resolver`. I'd double check that cocoapods is installed and that the assumptions in the settings is valid for your app.

Dependencies on native libraries are handled by Google's External Dependency Manager for Unity, which is bundled with our SDK.  https://github.com/googlesamples/unity-jar-resolver
