### ISSUE TITLE
Please allow for calling accountForFacebookSDKPreventingAppLaunch from Unity

### ISSUE THREAD

**Issue by derFunk** [BranchMetrics/unity-branch-deep-linking-attribution#21]
We're using the native Facebook SDK for Unity (which is the FB SDK plus the Unity wrappers).

Currently we're not able to call `accountForFacebookSDKPreventingAppLaunch` from within Unity, because it's not exposed, e.g. in `BranchiOsWrapper.mm`.

It would be nice if you could add this bridge method to be called from Unity prio to calling Branch.io's initSession().

**Comment by antonargunov** [comment]
Hi derFunk,
we will add this method in c# wrapper asap.

**Comment by antonargunov** [comment]
derFunk, update please Branch SDK

**Comment by antonargunov** [comment]
derFunk,
keep me in touch please how it works for you

**Comment by derFunk** [comment]
Thanks! Will do.

**Comment by antonargunov** [comment]
I hope all works perfect.

**Comment by derFunk** [comment]
Works well, sorry for my late response.
