### ISSUE TITLE
 iOS native plugin extern function name conflict

### ISSUE THREAD

**Issue by AFB-MORA** [BranchMetrics/unity-branch-deep-linking-attribution#211]
### Describe the bug

Native plugin extern function name "_logout()" conflict with other plugin's (OneSignal) function name "_logout()". General function names like "_logout()" should not be used. You can rename general names with "branch" prefix like Facebook's "IOSFBLogOut();" function.

This issue is not specific to OneSingal. If I write my own custom plugin with "_logout()" or "_setIdentity(string)" functions, I can still see same error. These names are too general and cannot be used.

### Steps to reproduce

1. Add OneSignal
2. Add Branch.io
3. Build iOS project
4. Archive Xcode project
5. You see duplicate symbols error

### Expected behavior

Build Xcode project successfully.

### SDK Version

1.0.0

### Unity Version

2022.3.10

### Make and Model

Xcode

### OS

iOS 17

**Comment by echo-branch** [comment]
@AFB-MORA 
Good catch, really surprised this issue hasn't been reported earlier. I'll add an internal ticket to handle this.

**Comment by echo-branch** [comment]
This is still planned work, just taking longer to get resources devoted to a Unity update.
