### ISSUE TITLE
Wrong Serialization of JSON callback

### ISSUE THREAD

**Issue by DerSnOr** [BranchMetrics/unity-branch-deep-linking-attribution#33]
Hi there

We were using the branch deep linking and added some extra information to metaData and tags of the GetShortUrl function just to see how the information would look like when installing the app on the second device.

However neither the BranchLinkProperties file nor the BranchUniversalObject had the information we needed. The problem was the faulty serialization of the JSON callback

This is the original code from BranchLinkProperties.cs:

```
public void loadFromDictionary(Dictionary<string, object> data) {
        if (data == null)
            return;

        if (data.ContainsKey("~tags")) {
            tags = data["~tags"] as List<string>;
        }
```

But data["~tags"] is a List<object> so we fixed this by:

```
public void loadFromDictionary(Dictionary<string, object> data) {
        if (data == null)
            return;

        if (data.ContainsKey("~tags")) {
            tags = new List<String>();
            foreach (object tagStr in (List<object>)data["~tags"])
            {
                tags.Add(tagStr.ToString());
            }
        }
```

Similiar with the metadata  in loadFromDictionary:

```
if (data.ContainsKey("metadata")) {
            if (data["metadata"] != null) {
                Dictionary<string, object> metaTemp = data["metadata"] as Dictionary<string, object>;

                if (metaTemp != null) {
                    foreach(string key in metaTemp.Keys) {
                        metadata.Add(key, metaTemp[key] as string);
                    }
                }
            }
        }
```

You try to serialize all values to a string here. So all Lists inside the metadata ($keywords, ~tags) get lost during this serialization.

**Comment by antonargunov** [comment]
@DerSnOr what version do you use?

**Comment by DerSnOr** [comment]
I'm sorry, but I cannot actually find any version number inside the plugin so I can't answer your question.
But the code snippets from BranchUniversalObject.cs and BranchLinkProperties.cs are still the same at the current version here on github.

**Comment by antonargunov** [comment]
@DerSnOr you are right about wrong "~tags" parsing, this issue is fixed. Update please SDK.
#34 

About "controls_params" and "metadata":
- these fields are used for your custom params
- you don't need read from "metadata" something like "~tags", "channels" and other params that UniversalObject and LinkProperties have
- when you add some "metadata" or "controls_params" into link we know what you added and you can parse by yourself your custom params, we just give you "key":"value" and you transform your "value" as you wish (int, list, etc.)

**Comment by DerSnOr** [comment]
@antonargunov 
Thanks for the fix.
Yeah the thing with the UniversalObject was not really blocking as we had the tags inside the LinkProperties. I just realized that the data got missing during the serialization.

**Comment by antonargunov** [comment]
@DerSnOr Great! Thanks!
