### ISSUE TITLE
No deep linking data arriving inside the app through facebook ad

### ISSUE THREAD

**Issue by Acimaz** [BranchMetrics/unity-branch-deep-linking-attribution#37]
Hey guys,
im not sure whether or not you tried to share your testbed app via a facebook ad, but i did it it doesnt work somehow..
When i share my branch link through WhatsApp, Email or even when i manually share it on facebook it works. But when i use facebook ads through the facebook dev console it doesnt. No data arrives inside the app, the universal objects seem to be empty.
Right now, im trying to figure out whether or not i have a wrong setup on the facebook platform but i dont think so. Im not using the facebook sdk as the branch doc says that it should work without it, simply in adding my facebook id etc on the dashboard But as i said it doesnt work.
Maybe its something inside the unity implementation? I dont know, i just wanted you to know of this issue! Our company is trying to use branch in unity to implement it in our apps, so it would be great if we could solve this problem together :D

**Comment by antonargunov** [comment]
Hello @Acimaz !
What version of SDK?
What platform?

**Comment by Acimaz** [comment]
Ah yes ofc:
Its the latest sdk from the master branch, so i think its Android 1.14.3 i think?
Its commit no. 31ec1f1.
And the platform is android API lvl 16 or higher.

**Comment by Acimaz** [comment]
Im a bit confused of what you mean when you write "Updating Branch to Android version 1.14.3 and iOS version 0.12.3" in commits, because there are commits in which you say "version 0.2.6" :D
What do you mean with those version numbers?

**Comment by antonargunov** [comment]
That are versions of native libs. We use native SDKs(libs) + wrappers in Unity3d.
Anyway, today we will upload new version of Unity SDK.
Right now new version is placed in branch "version-3.0".

Tomorrow you can use new version, there are a lot of changes in native libs.
Also new version supports new link scheme format (xxxx.app.link).

Btw, you can try new version right now, but for release I will make one minor change for "simulate fresh installs" mode (debug mode).

**Comment by Acimaz** [comment]
Alright them ill try this new version with facebook ads and inform you whether or not it worked.
Ill upload a new app into the store then with the new sdk. Is it safe just to import the .unitypackage into my project?
Yea i read the part of the SetDebug stuff :D

**Comment by antonargunov** [comment]
@Acimaz no, it is not save just to import, because SDK is re-worked and you should to read changelog.md and readme.md.

@Acimaz please! If this feature will not work, give me detailed step-by-step description how I can to reproduce that issue. Really too hard to work with issues like "it isn't work" :). I think you understand me very nice :)

**Comment by Acimaz** [comment]
Yes dude i know what you mean :)
Ill do my best!

**Comment by antonargunov** [comment]
thanks! :)

**Comment by Acimaz** [comment]
Am i correct in assuming that my "live custom domain" is kaasabranchtest because i set it like this on my branch dashboard? I need to add it to the prefab in the testBed app.

![capture](https://cloud.githubusercontent.com/assets/3418387/18278493/9d416f62-7452-11e6-8ce2-ce3d8e05ecbb.PNG)

**Comment by antonargunov** [comment]
No, that is "live app links", "live custom domain" works with old "bnc.lt"
"path prefix", "custom domain" is kept just for supporting old schemes

**Comment by Acimaz** [comment]
Ah, so i have to put "kaasabranchtest" into the live app links array

**Comment by antonargunov** [comment]
put full domain please "kaasabranchtest.app.link"

**Comment by Acimaz** [comment]
Alright Anton, heres a screen of my prefab just to keep you up to date:

![prefab](https://cloud.githubusercontent.com/assets/3418387/18303326/eb71369c-74dc-11e6-911e-fe315e0955f5.PNG)

I uploaded this as beta into the playstore and when its done im gonna configure a facebook ad campaign for it through our company.
The problem with facebook ads is that you cant test the deep link because it doesnt work when you send yourself a preview. So i decided to create a custom audience with 20 users (me incl.) and wait for the ad to pop up on my smartphone. That can take a while :/ 
If you want to get a ad too, just mail me your email which you are using on facebook. With luck, you will get the ad too :D

**Comment by Acimaz** [comment]
This is the current AndroidManifest:

![manifest_3](https://cloud.githubusercontent.com/assets/3418387/18303452/75734998-74dd-11e6-8203-07283818a972.PNG)

Creating a Google Android project and opening it in android studio the Manifest looks like this:

![androidstudio_manifest_3](https://cloud.githubusercontent.com/assets/3418387/18303525/d3cf8ae2-74dd-11e6-9674-eee14a31ae08.PNG)

I think everything look fine^^

**Comment by Acimaz** [comment]
Ah and ofc my branch dahboard android setup:

![branch_dashboard](https://cloud.githubusercontent.com/assets/3418387/18303800/22337ab2-74df-11e6-8ce7-2241fbd1dcd3.PNG)

**Comment by antonargunov** [comment]
Several words about links:
- if you set "app links" then "path prefix" and "custom domain" will be ignored

**Comment by Acimaz** [comment]
Yep, saw that in your code :D

**Comment by Acimaz** [comment]
Sadly it didnt work, i still dont get any deep linking data inside the app. The log looks like this after clicking on the facebook ad and downloading it on the play store:

![debug_info](https://cloud.githubusercontent.com/assets/3418387/18340709/c5a7c5aa-75a6-11e6-9b56-6b95ff090e2e.jpeg)

**Comment by Acimaz** [comment]
I added the following og tag on the branch dashboard now:

![branch_dashboard_02](https://cloud.githubusercontent.com/assets/3418387/18340745/f91610c2-75a6-11e6-88df-746f56b86c43.PNG)

The link i filled in is the branch marketing link, i hope this works now..

**Comment by antonargunov** [comment]
thanks for report

**Comment by Acimaz** [comment]
@antonargunov @aaustin Good news! I could fix this one through adding the following google play service library "play-services-basement-9.2.1 " into Assets/Plugins/Android
Those libraries are found at the following path: C:\Users\username\AppData\Local\Android\sdk\extras\google\m2repository\com\google\android\gms\play-services-basement\9.2.1 (pretty long, but yea..).
Basically there, where you installed the android sdk.

**Comment by Acimaz** [comment]
Hey @antonargunov , as you know i could fix the GAID thing but there is still one crucial problem.
If the app is not installed and i click on the Facebook Ad im redirected to the store. Then, when i install the app and open it, the app doesnt receive any deep linking data (the universal object is empty).

When i do the exact same thing (app not installed before) and click on the marketing branch link through WhatsApp and install the app after that, the deep linking data is shown and received by the app!

The only difference i could detect through ADB in Android Studio is the following:
1. When using the Facebook App, the click generates following lines:
   `09-15 12:41:25.228 969-1546/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=market://details?id=de.kaasahealth.branchTest flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.activities.LaunchUrlHandlerActivity (has extras)} from uid 10338 on display 0
   09-15 12:41:25.759 969-1569/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=http://market.android.com/details?id=de.kaasahealth.branchTest cmp=com.android.vending/com.google.android.finsky.activities.MainActivity (has extras)} from uid 10103 on display 0
   09-15 12:41:27.340 9821-9821/? I/Finsky: [1] com.google.android.finsky.utils.bl.run(147): Capture referrer for de.kaasahealth.branchTest (empty)
   09-15 12:41:28.741 9821-9821/? I/Finsky: [1] com.google.android.finsky.api.o.a(25782): Not delivering second response for request=[[ ] https://android.clients.google.com/fdfe/details?doc=de.kaasahealth.branchTest 0xe8d195d1 NORMAL 24]
   09-15 12:41:29.102 9821-9821/? I/Finsky: [1] com.google.android.finsky.api.o.a(25782): Not delivering second response for request=[[ ] https://android.clients.google.com/fdfe/rev?doc=de.kaasahealth.branchTest&n=20&o=0&sort=4 0xe8d195d1 NORMAL 29]
   09-15 12:41:29.172 9821-9821/? I/Finsky: [1] com.google.android.finsky.api.o.a(25782): Not delivering second response for request=[[ ] https://android.clients.google.com/fdfe/listCreatorContent?srcdoc=de.kaasahealth.branchTest&doc=developer-4755966280966839561&dt=1&ds=1 0xe8d195d1 NORMAL 30]
   09-15 12:42:17.169 969-1034/? D/PersonaManagerService: needVerificationForPackage de.kaasahealth.branchTest`
2. But when using the direct branch link (through WhatsApp or Mail or whatever):
   `09-15 12:46:29.435 969-1555/? I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=market://details?id=de.kaasahealth.branchTest&referrer=com.android.chrome flg=0x10000000 pkg=com.android.vending cmp=com.android.vending/com.google.android.finsky.activities.LaunchUrlHandlerActivity} from uid 10026 on display 0
   09-15 12:46:29.885 969-1571/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=http://market.android.com/details?id=de.kaasahealth.branchTest&referrer=com.android.chrome cmp=com.android.vending/com.google.android.finsky.activities.MainActivity (has extras)} from uid 10103 on display 0
   09-15 12:46:32.478 24306-24306/? I/Finsky: [1] com.google.android.finsky.utils.bl.run(149): Capture referrer for de.kaasahealth.branchTest
   09-15 12:47:30.925 969-1034/? D/PersonaManagerService: needVerificationForPackage de.kaasahealth.branchTest`

I can provide you with the full output if you want. I really need those deep link informations after the install :/

**Comment by Acimaz** [comment]
@antonargunov @aaustin Is it possible that we need something like this in the manifest?
`<receiver android:name="io.branch.referral.InstallListener" android:exported="true">
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
    </intent-filter>
</receiver>`

I saw this in one of alex blog posts.. im really desperately trying to get data through installs :D

**Comment by Acimaz** [comment]
@antonargunov Is it required maybe to implement the InstallListener.class to the BranchunityWrapper.class and use the "onReceive()" of the InstallListener to receive the intall string which we can appen in adding "&referrer=specialspecialString" to the redirection link on the dashboard?
If so, which "specialspecialString" do i have to provide?
In the sdk source code it calls this thing the "InstallationID".

**Comment by aaustin** [comment]
@antonargunov - I'll work with Ayhan on this one. It's unrelated to Unity I suspect.

**Comment by aaustin** [comment]
We discovered it was a bug on the Branch dashboard that prevented Ayhan from saving his Facebook access token, blocking our call to retrieve the data. We're getting it patched in production tomorrow morning.
