### ISSUE TITLE
Prefab auto prepends `https` when custom domain

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/unity-branch-deep-linking-attribution#43]
When a developer enters a custom domain into the App Links field, the prefab will automatically prepend `https`. However, when Branch links are created on custom domains, they are always `http`. See screenshot below:
![](https://cloud.githubusercontent.com/assets/3418387/18437802/e3ee939e-78fe-11e6-8609-216b420efb26.PNG)

The prefab needs to check if the App Link field contains `bnc.lt` or `app.link` and prepend the appropriate protocol.

**Comment by antonargunov** [comment]
@aaustin 
Now prefab auto prepends `http` when custom domain.

**Comment by Acimaz** [comment]
Nice 👍

**Comment by aaustin** [comment]
Uploaded to AWS
