### ISSUE TITLE
AndroidManifest.xml with missing icon and label

### ISSUE THREAD

**Issue by Acimaz** [BranchMetrics/unity-branch-deep-linking-attribution#45]
Hey there,
atm we are filling this fields in manually, but i think it would be good to write it into master.

The application field inside the AndroidManifest.xml is missing those tags mentioned above.
Atm they look like this:
`<application android:name="io.branch.referral.BranchApp">`

But if you want to be able to upload this into the play store there has to be a tag for the icon specified inside unity. Thats why this will help to show up the right icon and label in the apps manager on your smartphone:
`<application android:theme="@style/UnityThemeSelector" android:icon="@drawable/app_icon" android:label="@string/app_name" android:name="io.branch.referral.BranchApp">`

**Comment by Acimaz** [comment]
Just update the AndroidManifest.xml in Plugins/Branch/Android/AndroidManifest.xml and the editor script does the rest when creating a new manifest

**Comment by antonargunov** [comment]
@Acimaz thanks for report, manifest updated
