### ISSUE TITLE
_initSessionWithCallback etc missing in BranchiOSWrapper 0.3.0+ causing linker errors in XCode

### ISSUE THREAD

**Issue by dreamora** [BranchMetrics/unity-branch-deep-linking-attribution#51]
Since SDK 0.3.0 iOS projects can no longer be linked because Branch.cs refers to _initSessions functions that were removed from BranchiOSWrapper in commit 1a74f0c696a7effc0701c033654dd53e405d29b1 on Feb 28th

As Android does not have this problem and still supports callbacks this implies that this change to the BranchiOSWrapper was a 'cross SDK' side effect, not an intended change in this SDK.

**Comment by antonargunov** [comment]
@dreamora OMG! sorry, my mistake, will be fixed in 20 min
thanks for report!

**Comment by antonargunov** [comment]
@dreamora update please SDK from our github

**Comment by dreamora** [comment]
Great work, problem solved in 0.3.1 @antonargunov
