### ISSUE TITLE
"Simulate fresh install" does not log a install on dashboard

### ISSUE THREAD

**Issue by Acimaz** [BranchMetrics/unity-branch-deep-linking-attribution#53]
Currently, event when "simulate fresh install" is checked inside the app, the dashboard doesnt count 
it as 'install' but as 'open'.

**Comment by aaustin** [comment]
@antonargunov As long as each SDK call setDebug before getAutoInstance/initSession on Android and initSession on iOS, then this should happen.

**Comment by antonargunov** [comment]
@Acimaz I have changed realisation of "simulation of fresh installs" for Android, try please

**Comment by Acimaz** [comment]
It works 👍
