### ISSUE TITLE
Issues with Integration on Android

### ISSUE THREAD

**Issue by AIGameStudio** [BranchMetrics/unity-branch-deep-linking-attribution#54]
BranchSDK: Branch Warning: Please enter your branch_key in your project's res/values/strings.xml!
09-20 11:14:05.758  2255  2255 I art     : Rejecting re-init on previously-failed class java.lang.Class<io.branch.referral.BranchStrongMatchHelper$2>
09-20 11:14:05.758  2255  2255 I art     : Rejecting re-init on previously-failed class java.lang.Class<io.branch.referral.BranchStrongMatchHelper$2>
09-20 11:14:05.759  2255  2255 I art     : Rejecting re-init on previously-failed class java.lang.Class<io.branch.referral.BranchStrongMatchHelper$2>

AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: io.branch.referral.BranchStrongMatchHelper$2
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at io.branch.referral.BranchStrongMatchHelper.checkForStrongMatch(BranchStrongMatchHelper.java:58)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at io.branch.referral.Branch.onIntentReady(Branch.java:2064)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at io.branch.referral.Branch.access$900(Branch.java:70)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityResumed(Branch.java:2183)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.Application.dispatchActivityResumed(Application.java:214)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.Activity.onResume(Activity.java:1211)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at com.unity3d.player.UnityPlayerActivity.onResume(Unknown Source)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1281)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.Activity.performResume(Activity.java:6320)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5443)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
09-20 11:14:05.763  2255  2255 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
09-20 11:14:05.768  1217  6758 W ActivityManager:   Force finishing activity com.aistudio.testapp/com.unity3d.player.UnityPlayerActivity

If there is a bug or error in this repo, please file the issue here. 

If you need assistance integrating a Branch SDK, please email support@branch.io. Thank you.

**Comment by AIGameStudio** [comment]
You guys should tell that the Branch 2.4.0 sdk depends on "android-support-customtabs" and please update the Android Wrapper project dependencies to include 2.4.0 sdk instead of 2.3.0.

**Comment by antonargunov** [comment]
@AIGameStudio sorry, it was my mistake when I uploaded that version.
Please, wait a day, I will upload new version with fix and lib v2.4.2

**Comment by antonargunov** [comment]
@AIGameStudio , update please Unity SDK, you can download last version from github.
Changes:
- we added android-support-customtabs-23.3.0.jar (you can delete it if you have that library in other plugins)
- fixed some issues

**Comment by apaunov** [comment]
Hello BranchIO,

On our company app we are getting this exception when running on Android 6.0.1:

Note: Our company name has been replaced with "com.############" for privacy concerns

11-03 14:17:04.600: E/AndroidRuntime(2371): FATAL EXCEPTION: main
11-03 14:17:04.600: E/AndroidRuntime(2371): Process: com.############, PID: 2371
11-03 14:17:04.600: E/AndroidRuntime(2371): java.lang.NoClassDefFoundError: io.branch.referral.BranchStrongMatchHelper$2
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at io.branch.referral.BranchStrongMatchHelper.checkForStrongMatch(BranchStrongMatchHelper.java:58)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at io.branch.referral.Branch.onIntentReady(Branch.java:2102)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at io.branch.referral.Branch.access$1100(Branch.java:70)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityResumed(Branch.java:2225)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.Application.dispatchActivityResumed(Application.java:214)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.Activity.onResume(Activity.java:1207)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:443)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at com.openlane.ui.activities.base.AbstractActivity.onResume(AbstractActivity.java:175)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at com.openlane.ui.activities.splash.SplashActivity.onResume(SplashActivity.java:89)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.Activity.performResume(Activity.java:6312)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.os.Looper.loop(Looper.java:148)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at java.lang.reflect.Method.invoke(Native Method)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-03 14:17:04.600: E/AndroidRuntime(2371): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

We are not running Unity SDK but simply integrated the Branch IO in our app. We don't observe this issue when running on Andorid 5.1.1.

Could you please help us solve this issue?

Thank you!
