### ISSUE TITLE
Cant retrieve first referring campaign through Branch.getFirstReferringBranchUniversalObject();

### ISSUE THREAD

**Issue by Acimaz** [BranchMetrics/unity-branch-deep-linking-attribution#59]
Hey guys,
somehow there is a problem in our app retrieving the first referring universal object. It always seems to be empty. The dashboard looks like this:

![branch_dashboard_03](https://cloud.githubusercontent.com/assets/3418387/19076609/cb9103a2-8a49-11e6-93d3-85c9d5e68769.PNG)

As you can see, it resets to another campaign i previously used (i dont even know the time i used it the last time). But this shouldnt be the proper behaviour of the first referring link, right?

We are using the latest sdk from here, v0.3.3.

**Comment by aaustin** [comment]
Hey @Acimaz - Your dashboard looks like it's properly registering a referred session from that link in the far right hand column. However, you're saying that in the app, you're receiving no data when you opened up the app at 15:29:10?

Are you sure that's you and not someone else testing with that link at the time?

**Comment by aaustin** [comment]
Can you also send some client side logs using setDebug before you call initSession?

**Comment by Acimaz** [comment]
Hey @aaustin, yes im sure about it because noone else knows about that marketing link at the moment.
Because our app is really big it will take some time, but when im ready ill provide you with some logs!

**Comment by antonargunov** [comment]
Hi @Acimaz , you should to update Unity SDK.
Important notes:

1) you need to add into manifest into tag "application" that:
**android:name="io.branch.referral.BranchApp"**
If you use your own Application class - ping me.

2) we have extended UnityPlayerActivity, and you need to replace "activity" head with that:
<**activity android:name="io.branch.unity.BranchUnityActivity" android:launchMode="singleTask"**>
if you use your custom extended activity - ping me.

After your changes, try please your application.

**Comment by Acimaz** [comment]
@antonargunov Hey anton, thanks for the info! I was on holiday, so i couldnt write :)
As soon as we are going to make an update for our app i will update the SDK as well. At the moment everything is working smooth, thats why i wont update it for a while ^^

**Comment by aaustin** [comment]
I'm going to close this out assuming all is well!
