### ISSUE TITLE
App does not get data from universal link

### ISSUE THREAD

**Issue by TTPw1nd** [BranchMetrics/unity-branch-deep-linking-attribution#68]
Hi there,

Firstly, English is not my mother language so sorry if I'm not clear enough. Now, the situation is:

We have a game made with Unity.
We successfully implemented Branch for the Android version, everything works well.

For iOS version, we're currently stuck with this issue:

Tap on the universal link:

+ If the game is not installed, Branch works correctly: user will be redirected to Appstore, after installing then opening the game, user is redirected to the correct place in the game (according to the data we configured on Branch dashboard).

+ If the game is already installed, the game is opened, but nothing happens. My dev sees that the callback is not called.

We did further investigation and see that another 3rd party library has some kind interception. The library is Getsocial: www.getsocial.im

I contacted Getsocial and asked about "Several IMPL_APP_CONTROLLER_SUBCLASS" as indicated in your Troubleshooting section and here is their response:

```We tried to dig deeper, but havent found a solution. We do override UIApplication, but not AppController to implement deep linking, receive PN token, and handle actions after clicking on the ios notifications.```

Do you have any clue to help? Thanks a lot in advance.

**Comment by agrimn** [comment]
Hi phonggenix,

Our team has a new validation tool that allows us to check various information about your Xcode project configuration to make sure everything is configured properly.

The privacy and security of our partners are paramount, and as such the script does not collect or store:
Any of your apps code
Any of your project assets
Your developer email, or personal information

Once the configuration information is collected, the script sends it to Branch and returns a short-link you can follow to view the validation results. For exact instructions on running the script, I'd like to point you to the relevant docs page, found here:
https://dev.branch.io/getting-started/universal-linking-validator/

as well as the validator, which can be found here:
https://branch.io/resources/universal-links/

After running the local script, open the link in your web browser and enter your Branch Key and Secret to view the test results. If you aren't able to get your Universal Links working based on the validators feedback, it would be helpful if you could send me the link the local script returned to you, and any changes you might have made based on the validator's results. 

If this does not resolve your issue, please write in directly to integrations@branch.io, linking to this GitHub post and we'll get back to you as soon as possible!

**Comment by antonargunov** [comment]
Hi phonggenix, @ethanneff ,
provide me with info, where I can find file with IMPL_APP_CONTROLLER_SUBCLASS in Getsocial library.

**Comment by TTPw1nd** [comment]
Hi Anton,

Actually we had also tested with Branch Test App:

+ Everything works perfectly for both Android and iOS
+ Implement Getsocial (www.getsocial.im) into the Test App => Android still works perfectly, but iOS has this issue:

**Tap on the universal link:**

If the game is not installed, Branch works correctly: user will be redirected to Appstore, after installing then opening the game, user is redirected to the correct place in the game (according to the data we configured on Branch dashboard).

**But problem is here:** If the game is already installed, the game is opened, but nothing happens. My dev sees that CallbackWithBranchUniversalObject is not called.

So I think you can reproduce the issue yourself by using the Test App and add Getsocial. Please try!
Thanks a lot for your help.

Btw, as stated in the first message:

> I contacted Getsocial and asked about "Several IMPL_APP_CONTROLLER_SUBCLASS" as indicated in your Troubleshooting section and here is their response:
> 
> We tried to dig deeper, but havent found a solution. We do override UIApplication, but not AppController to implement deep linking, receive PN token, and handle actions after clicking on the ios notifications.

**Comment by antonargunov** [comment]
Hi @phonggenix , I have investigated that plugin, and I have found:

**1) Get Social plugin has deep linking implementation:**
http://docs.getsocial.im/?platform=unity#deep-linking

As I understood, that guys override methods: openUrl, continueUserActivity for deep linking and our plugin can’t do any.

**2) That is source code for iOS:**
https://github.com/getsocial-im/getsocial-ios-sdk/releases/tag/v5.2.1

As I understand, GetSocial doesn’t get access to framework source code, I can see libraries only and that means we can’t fix any in that plugin.

**Possible solution:**
Ask they to give you possibility to disable deep linking in that plugin.

**Comment by TTPw1nd** [comment]
Hi Anton,

Thanks for taking time to investigate and provide suggestion.
I've passed this suggestion to Getsocial team and am waiting for your response. Will keep you posted.

**Comment by antonargunov** [comment]
@phonggenix, feel free to ping us when you will need help

**Comment by TTPw1nd** [comment]
Hi Anton,

Sorry for late response. GetSocial provided me with a modified version of their SDK and everything works now. Thanks again.

**Comment by antonargunov** [comment]
Hi @phonggenix , nice to hear that!
Good luck!
