### ISSUE TITLE
MiniJSON in the Branch SDK creates a namespace conflict with other SDKs using MiniJSON

### ISSUE THREAD

**Issue by dwestgate** [BranchMetrics/unity-branch-deep-linking-attribution#69]
This is a partner-submitted request from Integrations Engineering:

In the Unity SDK, you're using MiniJSON. Unsurprising, as it's the de facto JSON parser for Unity. However, there are multiple versions of this floating round, everyone includes it in their SDK. Quite often the multiple versions collide with Other People's Plugins. One example, UniBill - one of the most prevalent In App Purchase plugins in use. 

A super-easy fix is to rename the MiniJSON  namespace to Branch_MiniJSON (or similar), fixup the references in BranchUniversalObject.cs, BranchLinkProperties.cs, and Branch.cs (and possibly some stuff in your demo dir).

**Comment by antonargunov** [comment]
Hello @dwestgate , thanks for report.
We fixed that issue in new version of Unity SDK.
New version is available for downloading.
