### ISSUE TITLE
IOS: Universal object is empty if I dont use a "marketing" link

### ISSUE THREAD

**Issue by thorning** [BranchMetrics/unity-branch-deep-linking-attribution#72]
I am trying to direct users to personlized content when they open an ios app, i.e. https://example.com/item/42 directs to item 42. The ids and links are dynamically created.

I have universal links setup, and when clicking the link, my app opens correctly without issue, but the universal object in the callback does not contain any values.

I tried creating a marketing link in the Branch dashbord "https://example.com/item" and this link work correctly, I can even do "https://example.com/item?id=42" to get the id.

Is there a way to simply get the url used to open app, or is using marketing links for this correct?

Best regards, Andreas

**Comment by antonargunov** [comment]
Hi @thorning , you can see in Universal Object metadata your link for example "https://xxxx.app.link/GhgHGghHG", but I think that is unusable for you.

You can do:
1) Create set of marketing links in Dashborad for each item and then send one link (in your game you will have list of links for each item).
You should add into metadata pair "item:item_number"

2) You can dynamically generate links in your app and send that links, and you should add into metadata pair "item:item_number" (like in Dashboard).

In your application you will check that the pair "item:item_number" (see metadata dictionary).

Note: Branch links don't work with params like usual web links, so if you want to have different values in links - you need to have different links with that different values.

**Comment by thorning** [comment]
Thanks for the quick reply.

It seems I cannot see the link in the metadata, if I did not create the link though the branch dashbord.

If I click [https://xxxx.app.link/test]() it will open the app correctly, but the universal object json is 
```
{
  "$canonical_identifier": "",
  "$content_type": "",
  "$exp_date": "0",
  "$keywords": [],
  "$og_description": "",
  "$og_image_url": "",
  "$og_title": "",
  "$publicly_indexable": "0",
  "metadata": {}
}
```

If I understand you correct I should have gotten the full link here, and then I could parse it myself and send the user to the right place?

If i create a marketing link for `/test` is will look like

```
{
  "$canonical_identifier": "",
  "$content_type": "",
  "$exp_date": "0",
  "$keywords": [],
  "$og_description": "",
  "$og_image_url": "",
  "$og_title": "",
  "$publicly_indexable": "0",
  "metadata": {
    "$marketing_title": "Test",
    "$one_time_use": "False",
    "+click_timestamp": "1484920330",
    "+clicked_branch_link": "True",
    "+is_first_session": "False",
    "+match_guaranteed": "True",
    "~creation_source": "1",
    "~feature": "marketing",
    "~id": "xxxx",
    "~marketing": "True",
    "~referring_link": "https://xxx.app.link/test"
  }
}
```

And I can even use [https://xxxx.app.link/test?id=1]() and the metadata will contain `{"id" : "1"}`, but from what you are saying this might be an unsupported feature?

I can make it work with a single marketing link with a dynamic parameter, but I cannot manually create a new marketing link for each id, as they are dynamically created. An advantage of this could be that I can integrate with some of the branch analytics tied to marketing links.

**Comment by antonargunov** [comment]
@thorning , 
> It seems I cannot see the link in the metadata, if I did not create the link though the branch dashbord.

yes, if should create a link through Branch Dashboard or through C# scripts from your project.

> if i create a marketing link for /test is will look like...
> And I can even use https://xxxx.app.link/test?id=1 and the metadata will contain {"id" : "1"}, but from what you are saying this might be an unsupported feature?

You should get your users "branch link" created through Branch Dashboard or through C# scripts from your project.
You can use feature "?id=1" if it works for you and for your needs.

> but from what you are saying this might be an unsupported feature?

Forget please about that, I had wrong thoughts about your needs.

**Comment by thorning** [comment]
Thank you for the help and fast response.

I got it working and am looking forward to trying it in practice.
