### ISSUE TITLE
Unity+IOS+Plugin VuFORIA === problema  

### ISSUE THREAD

**Issue by lucasunity** [BranchMetrics/unity-branch-deep-linking-attribution#73]
I am encountering an error while using the vuforia plugin in Unity. Simply when using the vuforia plugin, the branch does not get me any console. It is noted that when using on the android platform. I did not get problems, only in IOS. I need to use deeplinks but I do not get any info when I use the vuforia plugin (Augmented Reality)

**Comment by antonargunov** [comment]
Hi @lucasunity , I think Vuforia uses custom AppController.
You can read our readme.md to understand how you can solve that issue.

Also, in folder ThirdPartySolutions/CardboardSDK_ios you can see changed files to solve that issue between Branch SDK and Cardboard SDK.

**Comment by antonargunov** [comment]
@lucasunity one more possible trouble - you didn't tap button "update ios wrapper" and your key was not added to ios wrapper. Check please.

**Comment by lucasunity** [comment]
Yes
I clicked on update ios wrapper, problems persist

**Comment by antonargunov** [comment]
@lucasunity try please our solution for solving ios troubles between plugins.

**Comment by lucasunity** [comment]
I tested ThirdPartySolutions / CardboardSDK_ with the vuforia and continue to encounter problems. (I did update the wrapper). I did other tests, I created another blank project, I imported the branch.io project and I imported the Vuforia plugin. again. Replaces the files in ThirdPartySolutions / CardboardSDK_ and not the same problem.

**Comment by lucasunity** [comment]
The problem only happens for IOs, in android works perfectly

**Comment by antonargunov** [comment]
Hi @lucasunity , sorry for delay.
I don't understand why you use Cardboard solution for Vuforia.

Look please, that is our step-by-step solution:
https://github.com/BranchMetrics/unity-branch-deep-linking#several-impl_app_controller_subclass

That is solution for Cardboard and you can use that solution like an example "how to solve troubles with several AppController classes", you should not use Cardboard solution for Vuforia. That is just example in your case:
https://github.com/BranchMetrics/unity-branch-deep-linking/tree/master/ThirdPartySolutions/CardboardSDK_ios

**Comment by lucasunity** [comment]
That's what I needed. The problem really was the conflict between the App controller. Thank you very much for the help

**Comment by antonargunov** [comment]
@lucasunity, I glad to hear!
Good luck!

**Comment by carlosfarinhas** [comment]
@antonargunov you solved my problem too!
My Universal link redirected to scene when App was not installed, but if App was installed the link didn't redirect to scene.
I had to merge all AppControllers.mm into one.
I had to copy BranchAppController.mm and OpencvforunityAppController.mm to UnityAppController.mm. Then I commented Branch and Opencv AppControllers and it worked.
Thank you

**Comment by antonargunov** [comment]
@carlosfarinhas , thank you for your report!
