### ISSUE TITLE
Android App Link doesn't work when use FB App Invite feature

### ISSUE THREAD

**Issue by featalion** [BranchMetrics/unity-branch-deep-linking-attribution#77]
Hi,

I implement Facebook App Invites. I am able to share app invite on the FB, but when click on the invite in the Android FB app, I got redirect to the Google Play Store, instead of my app. That redirect does not supply any information to the application. In the logs (`adb logcat`) from the Android FB app I see the following:

> E fb4a.1jb: Native application url did not specify Android key hash.
> ActivityManager: START u0 {act=android.intent.action.VIEW dat=market://details?id=MY-APP-BUNDLE-ID&referrer=utm_source=apps.facebook.com&utm_campaign=fb4a

Note: `MY-APP-BUNDLE-ID` is right one, I replaced it to post here.

SHA256 certificate fingerprint is supplied via Branch's dashboard.
In the Open Graph Object Debugger an app link looks reasonable, but doesn't contain app key hash:

> my-app-prefix://referrer_player_id/8c1c19d0-7c18-11e6-b564-595eb34adaf7?link_click_id=link-367670459015568204

It looks like App Link construction goes wrong and does not add required fields, at least the Android FB app says that. I don't know it happens in the Unity plugin, Android library, or on Branch's servers, but it makes FB App Invites useless. At the same time, direct links, i.e. `xxxx.test-app.link/...`, works as expected, they open application directly through select app dialog.

I appreciate any help, thanks in advance!

P.S. I made support ticket as well.

**Comment by antonargunov** [comment]
Hi @featalion , thanks for report.
We have started investigation of that issue.

**Comment by antonargunov** [comment]
@featalion do you use last version of Branch SDK?
If no - try to update Branch SDK please.

**Comment by featalion** [comment]
@antonargunov yeah, I use the latest version of SDK

**Comment by featalion** [comment]
@antonargunov do you need more information about FB app configuration, AndroidManifest.xml, etc.?

**Comment by featalion** [comment]
After update to Unity3D 5.5 from 5.3 the bug disappeared.

**Comment by antonargunov** [comment]
@featalion thanks for report!
