### ISSUE TITLE
Fabric Integration Issue

### ISSUE THREAD

**Issue by AIGameStudio** [BranchMetrics/unity-branch-deep-linking-attribution#79]
We are trying to integrate Branch Unity SDK with Fabric. As per your documentation you have mentioned that to support Fabric we need to include BranchThirdParty.jar and update the manifest file to include CustomApplication and CustomActivity. After doing the required steps when i am trying to build the project i am getting this error

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lio/branch/unity/BuildConfig;
1 error; aborting
]

Can you please help us out in sorting this issue.

**Comment by antonargunov** [comment]
Hi @AIGameStudio , I will answer you soon.

**Comment by antonargunov** [comment]
Hi @AIGameStudio , did you use solution from folder ThirdPartySolutions?
I don't understand which BranchThirdParty.jar you added.

**Comment by antonargunov** [comment]
@AIGameStudio , I solved that issue.
**Update please BranchThirdParty.jar**
https://github.com/BranchMetrics/unity-branch-deep-linking/tree/master/ThirdPartySolutions/Fabric_IO_droid

**Also, change please that:**
Change android:name to "io.branch.anroidthirdparty.BranchCustomApplication" in tag application
Change android:name to "io.branch.anroidthirdparty.BranchCustomActivity" in tag activity

**Comment by abhicoo** [comment]
@antonargunov 
What i did to fix the issue was to create generate new BranchThirdParty.jar without BuildConfig.class in it.

The BuildConfig.class was clashing with other BuildConfig.class which was using the same same namespace.

**Comment by antonargunov** [comment]
@abhicoo , yes, are you right, I know that issue with BuildConfig.class.
It worked in old Unity, but in newer version it doesn't work.
To avoid any troubles in the future I just changed namespace for ThirdPartyPlugin and keep BuildConfig.class.

**Comment by vfilho** [comment]
I'm using the Unity 2017.1.1f1 and trying build to android with Branch.IO and Fabric, but now is happening this problem:

```
Execution failed for task ':transformResourcesWithMergeJavaResForRelease'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK fabric/io.fabric.sdk.android.fabric.properties
  	File1: /Users/valerioantoniodallapiculafilho/Projetos/quizjam-unity/Temp/gradleOut/libs/BranchThirdParty.jar
  	File2: /Users/valerioantoniodallapiculafilho/Projetos/quizjam-unity/Temp/gradleOut/build/intermediates/exploded-aar/gradleOut/fabric/unspecified/jars/classes.jar
```

Please can you help me with this!?

**Comment by antonargunov** [comment]
Hi @vfilho , update please BranchThirdParty.jar
https://github.com/BranchMetrics/unity-branch-deep-linking/tree/master/ThirdPartySolutions/Fabric_IO_droid
