### ISSUE TITLE
reference to incorrect keys in RewardsHistoryPanel.cs

### ISSUE THREAD

**Issue by eps-git00** [BranchMetrics/unity-branch-deep-linking-attribution#82]
Looks like a cut and paste error in here. Uses of keys for "amount", "date" and "bucket" all check against a key of "type" rather than the correct key in RewardsHistoryPanel.cs, see items marked "WRONG KEY" in the snippet below:

        if (dict.ContainsKey("transaction")) {
            Dictionary<string, object> transactionDict = dict["transaction"] as Dictionary<string, object>;
            
            if (transactionDict != null) {
                if (transactionDict.ContainsKey("type") && transactionDict["type"] != null) {
                    strRes += "type = " + transactionDict["type"].ToString();
                }
                
                if (transactionDict.ContainsKey("id") && transactionDict["id"] != null) {
                    strRes += "  id = " + transactionDict["id"].ToString();
                }

//               WRONG KEY!!! 
                if (transactionDict.ContainsKey("type") && transactionDict["type"] != null) {
                    strRes += "  bucket = " + transactionDict["bucket"].ToString();
                }

//               WRONG KEY!!!                
                if (transactionDict.ContainsKey("type") && transactionDict["type"] != null) {
                    strRes += "  amount = " + transactionDict["amount"].ToString();
                }
                
//               WRONG KEY!!! 
                if (transactionDict.ContainsKey("type") && transactionDict["type"] != null) {
                    strRes += "  date = " + transactionDict["date"].ToString();
                }
            }

**Comment by antonargunov** [comment]
@eps-git00 , thank you for report! it will be fixed in the next version
