### ISSUE TITLE
Branch do not send any events to Answers

### ISSUE THREAD

**Issue by zarkov** [BranchMetrics/unity-branch-deep-linking-attribution#83]
Hi everyone, I hope you can help :)

So we have integrated Crashlytics and enabled Answers. 
Answers version is 1.3.10 -> all the analytics works fine

Then we have integrated Branch.io in v0.3.12

And took the BranchThirdParty.jar to get io.branch.anroidthirdparty.BranchCustomActivity and io.branch.anroidthirdparty.BranchCustomApplication so that there is no conflict.

Everything seems to work like a breeze, except Branch.io is not sending the 'Branch install' and 'Branch open' events like said in the documentation.

**Comment by antonargunov** [comment]
Hi @zarkov , show please your android manifest

**Comment by zarkov** [comment]
Of course, here it comes:
[AndroidManifest.txt](https://github.com/BranchMetrics/unity-branch-deep-linking/files/913530/AndroidManifest.txt)

**Comment by antonargunov** [comment]
@zarkov , try to update Unity SDK to v.0.3.13

**Comment by zarkov** [comment]
SDK updated to v.0.3.13, but no luck it is not working.

**Comment by antonargunov** [comment]
@zarkov , I have checked our testbed with fabric + answers.
All works for me.

1) What plugin do you use for Facebook?
2) What plugin do you use for "universal.tools.notifications"?

**Comment by zarkov** [comment]
@antonargunov I'll try the testbed during this weekend to validate that it works on my side too.

1. It is the native facebook unity sdk in version 7.7.0 (we are not on the last one since it messes up our DEX, and going constantly to the Android Studio to finalize builds would be quite the time eater during development)
2. It is UTNotifications version 1.6.2

**Comment by antonargunov** [comment]
@zarkov I will try to use that plugins in our testbed.

**Comment by antonargunov** [comment]
Hi @zarkov , how is it going?

**Comment by zarkov** [comment]
Hi @antonargunov,

I forgot it was easter weekend, my bad.
I did the test with only Branch and Fabric, it does not seem to work, I do not get any 'Branch Open' event.

Here i attach you the project: 
[TestBranchWithFabric.zip](https://github.com/BranchMetrics/unity-branch-deep-linking/files/930456/TestBranchWithFabric.zip)

I put 'xxxx' in Branch.prefab, FabricSettings and also in Plugins/Android/fabric/AndroidManifest.xml
So if you want to try it with this project you have to change it accordingly.

I do not get what i might be doing wrong.

**Comment by antonargunov** [comment]
Hi @zarkov ,
I tried your project.
I used my our Branch key etc. and your bundle id and fabric properties.
All works for me.

That is an archive with screenshots from my android device.
https://www.dropbox.com/s/w50kuv15l1v809y/issue_83_screenshots.zip?dl=0

I think you have incorrect Branch settings.
Please ping our integration team to check your settings.

**Comment by zarkov** [comment]
Hi @antonargunov ,
I looked at your screenshots and i get the same thing, it is just that Answers from Fabric doesn't display any of the events 'Branch Open/Install/Share' on there dashboards.
I will try to get in touch with the integration team.
Thank you for your help.

**Comment by antonargunov** [comment]
@zarkov ,
do you send that events by yourself?
we don't send any events to fabric.

Look at that screenshot please.
https://www.dropbox.com/s/5phip9u71c4g0w6/Screenshot%202017-04-20%2016.34.28.png?dl=0
You can see Fabric is processing our testbed (I connected to Fabric on April 13 and you can see one user).
That means - all works.

Try to send events by yourself from Branch callbacks.

**Comment by zarkov** [comment]
@antonargunov that is working on my side too.

I am talking about [this](https://dev.branch.io/third-party-integrations/fabric-answers/guide/)

In the doc it is written:
"_Branch will automatically send the following three events to Answers:_
- _Branch Install: This event is sent when a user installs your app after clicking a Branch link._
- _Branch Open: This event is sent when a user clicks a Branch link but already has your app installed._
- _Branch Share: This event is sent when the has shared a link on a channel using the Branch share sheet._"

**Comment by antonargunov** [comment]
@zarkov ,
As I know, that events will work with native Android SDK and with native iOS SDK.
For Unity and Xamarin SDK we use clear native Branch libs, without additional integrations or dependencies.

**Comment by antonargunov** [comment]
@zarkov ,
BranchThirdParty.jar was created for resolving conflicts between Branch and Fabric and doesn't contain any interactions between Branch and Fabric.

**Comment by zarkov** [comment]
@antonargunov ,
Thanks for clarifying that.

If i understand correctly, it should be us that integrates the logic for sending "Branch Install" "Branch Open" "Branch Share" on Unity.

Will there be an integration of those interactions in the future for the Unity SDK ?

Ps: Might be a good idea to add that information in the documentation, where it clearly states that these events are not sent automatically when using the Unity and Xamarin SDK.

**Comment by antonargunov** [comment]
@zarkov , you are welcome! :)

> If i understand correctly, it should be us that integrates the logic for sending "Branch Install" "Branch Open" "Branch Share" on Unity.

yes

> Will there be an integration of those interactions in the future for the Unity SDK ?

No in the nearest future. I worked/am working with many plugins for Unity and the best way is to keep plugin without dependencies and etc. and in different libs/modules, else it will be a big trouble.

> Ps: Might be a good idea to add that information in the documentation, where it clearly states that these events are not sent automatically when using the Unity and Xamarin SDK.

yes, are right,
I have send a request to our team.

Thanks!

**Comment by aaustin** [comment]
Hey team - I bet the Crashlytics/Answers Unity SDK doesn't support the integration. Let me check with the Fabric team on the best course of action here. More soon!
