### ISSUE TITLE
cannot use '@try' with Objective-C exceptions disabled

### ISSUE THREAD

**Issue by dmeinrath** [BranchMetrics/unity-branch-deep-linking-attribution#87]
Xcode builds are now dying with this error:

Builds/iOS/Libraries/Plugins/Branch/iOS/Branch-SDK/Requests/BranchInstallRequest.m:43:9: [31mcannot use '@try' with Objective-C exceptions disabled[0m

@try {
[36m^[0m

[33m>[0m [39;1mCompiling[0m NSMutableDictionary+Branch.m

**Comment by dmeinrath** [comment]
using XCode 8.3.3 + Unity 5.6.2

**Comment by antonargunov** [comment]
@dmeinrath let me check

**Comment by antonargunov** [comment]
@dmeinrath I can't reproduce that issue in our TestBed.
Try to enable Objective-C Exceptions in xcode project.

https://www.dropbox.com/s/j81btmlxp6v19pv/Screenshot%202017-07-21%2010.20.41.png?dl=0

**Comment by dustinkerstein** [comment]
I've seen this happen a few times, but haven't figured out how to really isolate it. Seems a bit fluky. Using XCode 8.3.2 and Unity 2017.1.0f3

**Comment by dmeinrath** [comment]
@antonargunov we have, the worst part is that it seems random when the @try error occurs.

**Comment by antonargunov** [comment]
@dmeinrath ,

Unity3d doesn't add several properties into .xcodeproj for PBXNativeTarget "Unity-iPhone" and for PBXProject "Unity-iPhone" and xcode use default values for that properties.

Properties:
 * GCC_ENABLE_OBJC_EXCEPTIONS
 * CLANG\ENABLE_MODULE

You should set that properties with "YES" in xcode in tab "Build Settings":
 * Apple LLVM 9.0 - Language - Objective C (Enable Objective-C Exceptions)
 * Apple LLVM 9.0 - Language - Modules (Enable Modules C and Objective C)

**Comment by shirkan** [comment]
Facing this issue also with Unity Cloud Build.
Branch SDK 0.3.25, Unity 2017.2.0f3, XCode 9.
In Unity cloud build you cannot change this properties manually, but I see they are being set in BranchPostProcessBuild.cs.
Can you please suggest a different solution?
Thanks.

**Comment by shirkan** [comment]
Hi,
In BranchPostProcessBuild.cs I added debug logs to ChangeBranchBuiltProject, but couldn't see them on build end.
Changed:
`[PostProcessBuild(900)]`
to
`[PostProcessBuild(0)]`

and now it works.
Keep in mind we have other post processing procedures... please check.

**Comment by abelevtsov** [comment]
You can try to use something like this stupid and simple (works for me):
```csharp
#if UNITY_IPHONE
using System;
using System.IO;
using System.Text;

using UnityEngine;
using UnityEditor;
using UnityEditor.Callbacks;

public class IPhoneBuildPostprocessor : MonoBehaviour
{
    [PostProcessBuildAttribute(1)]
    public static void OnPostprocessBuild(BuildTarget target, string pathToBuiltProject)
    {
        Debug.Log("IPhone Script. Executing post process build phase.");
        Debug.Log("Path to XCode project: " + pathToBuiltProject);
        var xcodeProjectPath = Path.Combine(pathToBuiltProject, "Unity-iPhone.xcodeproj");
        var pbxPath = Path.Combine(xcodeProjectPath, "project.pbxproj");
        var xcodeProjectLines = File.ReadAllLines(pbxPath);
        var sb = new StringBuilder();
        foreach (var line in xcodeProjectLines)
        {
            if (line.Contains("GCC_ENABLE_OBJC_EXCEPTIONS") ||
                line.Contains("GCC_ENABLE_CPP_EXCEPTIONS") ||
                line.Contains("CLANG_ENABLE_MODULES"))
            {
                var newLine = line.Replace("NO", "YES");
                Debug.Log(line);
                sb.AppendLine(newLine);
            }
            else
            {
                sb.AppendLine(line);
            }
        }

        File.WriteAllText(pbxPath, sb.ToString());

        Debug.Log("IPhone Script. Finished executing post process build phase.");
    }
}
#endif

**Comment by csalmi-branch** [comment]
@dmeinrath are you still experiencing this issue, or did the above workaround help resolve the problem?

**Comment by fahall** [comment]
@antonargunov 

This still seems to be an issue when using Unity Cloud Build. I get the error listed above using 0.5.4 w/ Unity Cloud Build (tried Unity 2017.2.1f1 & 2017.4.18f1 LTS). I have not tried the workaround yet.

Edit: Not sure what was going wrong. I tried again this afternoon (without the workaround), and everything built fine on 2017.2.1f1 on Unity Cloud Build. I performed one successful build on each of  XCode versions 9.0, 9.4, and 10.1.

**Comment by fahall** [comment]
@antonargunov 

Okay, here is a bit more information:

- I **can** compile w/ Cloud Build just fine w/ 2017.2.1f1. 
- I **cannot** compile w/ Cloud Build using Unity 2017.4.18fi. I get the following error:

`Libraries/Plugins/Branch/iOS/Branch-SDK/Branch-SDK/BranchUniversalObject.m:513:9: cannot use '@try' with Objective-C exceptions disabled`

I tried using XCode versions 9.0, 9.4, and 10.1. I get the same error in all cases. I also tried Branch versions 0.5.4 and 0.4.5. 

Any thoughts on what I can try next?

**Comment by antonargunov** [comment]
@fahall thanks for report, I will re-check cloud building with our testbed, but I have thoughts unity cloud works wrong with project file in some cases.

**Comment by tommygwu** [comment]
Would be great to get Branch working with Unity 2017.4.18f LTS because that's the version Unity is adding long term support for.

**Comment by antonargunov** [comment]
I used cloud building for empty project with Branch Unity SDK.

**Environment:**
Unity3d 2017.4.18f1
xcode 10.1

**Result = SUCCESS:**
1: No Library cache found - ALL assets will be re-imported.
2: [Unity] Initialize engine version: 2017.4.18f1 (a9236f402e28)
...
40: publishing finished successfully.
41: Finished: SUCCESS

**Screenshot:**
https://www.dropbox.com/s/amhs403f3orlkkg/Screenshot%202019-01-29%2023.49.08.png?dl=0
