### ISSUE TITLE
AndroidManifest Activity improvement suggestion

### ISSUE THREAD

**Issue by czanier** [BranchMetrics/unity-branch-deep-linking-attribution#89]
Hi there, this is just a suggestion for the Branch automatic Android manifest setup. Current implementation looks for an activity with name "BranchUnityActivity" this works fine when you only have Branch installed but once you have multiples libraries or your own Activity like our case, we lose this auto-setup feature. Digging in the code we found out that BranchEditor.cs it's looking for this hardcoded Activity, since Unity only support one activity with "launchMode - singleTask."(1) attribute, we can relay in that attribute and leave the name of the activity to be overridden. 
This is the patch we are using, would it be possible to have similar support? what we did it's just a workaround. 
```
Index: Assets/Branch/Editor/BranchEditor.cs
--- Assets/Branch/Editor/BranchEditor.cs
+++ Assets/Branch/Editor/BranchEditor.cs
@@ -184,8 +184,9 @@
 			}
 
 			if (node.Name == "activity") {
-				foreach(XmlAttribute attr in node.Attributes) {
-					if (attr.Value.Contains("BranchUnityActivity")) {
+				foreach(XmlAttribute attr in node.Attributes)
+				{
+					if (attr.Name.Contains("launchMode") && attr.Value == "singleTask") {
 						unityActivityNode = node;
 						break;
 					}
@@ -194,7 +195,7 @@
 		}
 
 		if (unityActivityNode == null) {
-			Debug.LogError("Current Android Manifest was broken, it does not contain \"<activity android:name=\"io.branch.unity.BranchUnityActivity\">\"");
+			Debug.LogError("Current Android Manifest was broken, it does not contain an activity with launchMode=\"singleTask\"");
 			return;
 		}
```
(1) https://docs.unity3d.com/Manual/android-manifest.html

**Comment by antonargunov** [comment]
Hi @czanier , thanks for your post.
I will change our version tomorrow.
