### ISSUE TITLE
Multiple errors when trying to build to ios device on latest version

### ISSUE THREAD

**Issue by josh-flyclops** [BranchMetrics/unity-branch-deep-linking-attribution#99]
Hello,

I'm am getting multiple (what it seems to be) complier errors when trying to build to my ios device on xcode.

![screen shot 2017-09-26 at 1 09 35 pm](https://user-images.githubusercontent.com/3627920/30873786-5c1b8a56-a2bc-11e7-9867-a8261e8f04c6.png)
![screen shot 2017-09-26 at 1 10 25 pm](https://user-images.githubusercontent.com/3627920/30873790-5e8b636a-a2bc-11e7-8378-4c7bdbd8a6c5.png)

And here are the errors collapsed for the __weak and __strong issues:
![screen shot 2017-09-26 at 1 11 14 pm](https://user-images.githubusercontent.com/3627920/30873833-82a72e6e-a2bc-11e7-8011-e357a98c0236.png)
![screen shot 2017-09-26 at 1 11 26 pm](https://user-images.githubusercontent.com/3627920/30873834-841363ee-a2bc-11e7-9f35-0c827fe52073.png)

I am using xcode 8.3.3, unity 5.6.2f1, and the branch unity sdk 0.3.21.
And I was able to reproduce this using the demo that is provided.

**Comment by aaaronlopez** [comment]
Hi @josh-flyclops, we are aware of this issue and will roll out a fix for it soon. In the meantime, I recommend adding two underscores to the front of `typeof` changing it to `__typeof`. That should fix it.

**Comment by josh-flyclops** [comment]
Awesome, that worked. Thank you!
